### ISSUE TITLE
My profiler is indicating high CPU usage values

### ISSUE THREAD

**Issue by Gitoffthelawn** [Synzvato/decentraleyes#101]
According to *about:performance* in Firefox 47, Decentraleyes is requiring 5-8% CPU usage and is having a high number of medium-impact framerate events.

Compared to other extensions, it has a substantial performance impact according to that metric.

**Comment by Synzvato** [comment]
@Gitoffthelawn The performance on my end is comparable to that of ```uBlock Origin``` (both add-ons have ~1% of CPU usage, and the latter had 10 additional medium-impacts when last measured).

**Comment by Gitoffthelawn** [comment]
First, let me get the low hanging fruit out of the way: I don't think we want to compare your fine work to another extension that is a bit of hog.  I think you can aspire to be better!

Okay, now moving on to the important stuff.  The metric being discussed is *about:performance*.  Is that a good metric?  Honestly, I don't know (yet).  I've reviewed the code for it quickly, and at this time, I have more questions than answers.  Let's make sure in our discussions that we remember that the metric itself might have issues.  I have already become knowledgeable about one issue in it that can make the values meaningless for a handful of specific extensions.  That issue, however, should not apply to Decentraleyes.

To perform some tests, I created a fresh Firefox installation with 50 extensions.  I then let the machine sit unused for two hours recording metrics with only a single empty tab.  I chose this type of testing due to my own time constraints, not due to it being the ideal methodology.

Here are the results:

        Decentraleyes seems to have slown down Firefox very often. When this happens, the slowdown is generally noticeable.

        Impact on framerate: 0 high-impacts, 869 medium-impact.
        CPU usage: 1% (total 648925ms).
        System usage: 1% (total 96ms).
        Blocking process calls: 0% (total 0ms).

Of the 50 extensions that were installed, only 4 showed any medium-impact framerate events.  Of those 4, Decentraleyes caused the highest number of events, but by a statistically *insignificant* delta.

So, what's causing this?  Two distinct possibilities:
  1. *about:performance* results are meaningless in this context.
  2. The testing methodology is somehow biased against Decentraleyes.  This is unlikely, as Decentraleyes only needs to work hard when the browser is loading pages.  All the same, we need to be open to this possibility.
  3. Decentraleyes currently has some sort of issue that negatively impacts browser performance.

Which one is it?  I dunno.  I think profiling Decentraleyes might help figure it out.  I wish I had the time to do that, but, unfortunately, I'm still overbooked at this time.

**Comment by xenithorb** [comment]
I'm noticing severe performance problems on Dev Edition 49.0a2 on Linux, to the point where I had to disable it. On occasion, some pages never finish loading, either.

**Comment by Synzvato** [comment]
@Gitoffthelawn Thanks for sharing some more results!

> I don't think we want to compare your fine work to another extension that is a bit of hog. I think you can aspire to be better!

Like uBlock Origin (which is known to be [exceptionally efficient](https://github.com/gorhill/uBlock#performance)), Decentraleyes has to analyze every single request that leaves your computer. It does a pretty good job at promptly releasing requests that are not interesting, but it might still negatively impact this particular performance statistic.

To quote Nils Maier, the author of another Firefox memory inspector:
> Dear press: No, it is not OK to install this add-on along with the Top 20 or something add-ons and publish articles singling out the "biggest memory wasters" or something along the lines of this. This is wrong, superficial, sensationalist and outright wrong.

In the case of Decentraleyes, the statistics do not weigh the benefits (e.g. pretty much no response latency) against the amount of milliseconds it takes for the extension to make a decision.

Please also keep in mind that half of the current extension (including all response interceptions) can be thrown away once Firefox starts allowing add-ons to ignore ```Content Security Policies```. I think that the ```WebExtensions``` port should be our top priority at this point, as it could improve things tremendously.

@xenithorb

I'm sorry to hear that you've been experiencing difficulties. This kind of behavior hasn't been reported before. I would be very interested in knowing what other add-ons you have installed as I suspect it could be a conflict. About the page loads, does it happen with specific pages, or randomly?

**Comment by Gitoffthelawn** [comment]
@Synzvato I agree!  The benefits ***definitely*** outweigh the costs.

The *about:performance* stats might be revealing an underlying bug in Decentraleyes... or not.  Sometimes stats like that are very helpful as they help discover an issue with the code that is not obvious.  Other times, the stats are just a reflection of weaknesses in the metric-generation system.  I encourage you to see if it could be the former, and to perhaps file a bugzilla report if it's the latter.

In regards to uBlock Origin, much of the data provided by that developer is for a very old version of that code as well as comparisons to outdated versions of competing products.  You'll probably agree that testing old versions makes the comparisons useless.

In addition, that developer has an established history of publishing biased comparisons, rendering them useless.  For example, take a close look at his comparisons of Ad Blockers.  The last time I looked (which was a long time ago), the Ad Blockers were compared while using different block list subscriptions.  That's an incredibly biased way to compare performance and effectiveness.

A long time ago, I donated a significant amount of my time by helping with the documentation and wiki of that project.   A portion of my work involved improving the accuracy of those comparisons.  The developer responded by blocking me from the uBlock Origin repo.

Back to the important stuff: In regards to the post by @xenithorb: I have occasionally experienced the same symptom, but, just for myself, I have not yet concluded if it has anything to do with Decentraleyes.  That's another data point that could be helpful if other people report experiencing the same issue.  Since that's a different issue, but possibly related, @xenithorb would you mind creating a new issue for that?

**Comment by Synzvato** [comment]
@Gitoffthelawn

> The ```about:performance``` stats might be revealing an underlying bug [...]. I encourage you to see if it could be the former, and to perhaps file a bugzilla report if it's the latter.

I have no reason to think that the current code is not performing well, since all personal tests indicate that it's running fine. It's an open-source community project so feel free to fire away.

> In regards to uBlock Origin, much of the data provided [...] is for a very old version of that code as well as comparisons to outdated versions of competing products. You'll probably agree that testing old versions makes the comparisons useless.

I wouldn't call tests performed in september of last year old. I'm quite sure that it's still using the very same underlying foundation. So I don't agree with you there.

> In addition, that developer has an established history of publishing biased comparisons, rendering them useless. For example, take a close look at his comparisons of Ad Blockers. [...] The last time I looked [...], the Ad Blockers were compared while using different block list subscriptions.

As described [here](https://github.com/gorhill/uBlock/wiki/Firefox-version:-benchmarking-memory-footprint#setup), they loaded the exact same filter lists into both candidates.

> In regards to the post by @xenithorb: I have occasionally experienced the same symptom, but, just for myself, I have not yet concluded if it has anything to do with Decentraleyes.

Then let's discuss it here until we know what it is, and if it's actually caused by this add-on. As of now, it's a vague performance issue that fits quite well within this conversation. It might also be best not mention behavior that _might_ or _might not_ be caused by Decentraleyes to keep matters clear.

**Comment by Gitoffthelawn** [comment]
I don't want to spend any more of my time on it, so please take a quick look at the main uBlock Origin GitHub page.  Given that we are talking about performance here, take a *very careful* look at the CPU usage graph.  It only compares outdated versions of all the content blockers.  It does not even say what browser was used, or what version of the browser was employed.  It does not even specify which CPU or operating system were used for testing.  At best, the graph is meaningless.  At worse, it's deceptive.

Now, if you want, take a look at the "Memory" graph on that same page.  Again, it is testing old versions of all the products on an unknown operating system.  Curiously, it performs the Firefox memory test on an old version of 64-bit Firefox.  An overwhelming majority of systems don't use that version.  It has known memory issues, so performing memory testing on it results in biased data.

I don't agree with you that you can just say something is "still using the very same underlying foundation" and therefore conclude outdated testing is somehow still relevant.  No offense, but that's not good science.  The Intel i7 has largely the same underlying foundation as an old Pentium processor, or even the 8086 for that matter.  Apples and oranges, my friend.

**Comment by Synzvato** [comment]
> I don't want to spend any more of my time on it, so please take a quick look at the main uBlock Origin GitHub page. [..] At best, the graph is meaningless. At worse, it's deceptive.

That's quite a bold statement to make about the documentation of an add-on that's free of charge, falls under a great license, does not accept donations, takes user privacy extremely seriously, and is praised by its users. Would you call third-party benchmarks like [this one](https://www.raymond.cc/blog/10-ad-blocking-extensions-tested-for-best-performance/) potentially deceptive as well?

> I don't agree with you that you can just say something is "still using the very same underlying foundation" and therefore conclude outdated testing is somehow still relevant. No offense, but that's not good science [...]. Apples and oranges, my friend.

No offense taken. A lot of decisions are based off science papers that are more than a couple of years old. In my opinion, these graphs do a great job of showing off the creator's personal findings. People are free to do perform custom benchmarks. It's open source, and the replication guides are public.

> No offense, but that's not good science. The Intel i7 has largely the same underlying foundation as an old Pentium processor, or even the 8086 for that matter.

With that, you implicitly say that if you would want to do (near) perfect science, you'd need to perform these tests on your own personal machine under strict, representative, conditions. I fully agree with you, and people interested in such things are free to do so at their own convenience.

**Comment by Gitoffthelawn** [comment]
Thanks for your comments.  I don't want to spend more of my time on this discussion.  Let's agree to keep this issue on topic.
