### ISSUE TITLE
Offer direct insight in what the extension replaces

### ISSUE THREAD

**Issue by Huluti** [Synzvato/decentraleyes#102]
Hi ! 
First, thank you for this extension, the concept is very great :+1: 
However, I think that it could be better if we could see what extension have "replaced" by an icon with number of scripts. It's looks like HTTPS Everywhere, Privacy Badger and many others.

Thank you in advance.

**Comment by Gitoffthelawn** [comment]
What purpose would that information serve besides letting you know it's working?

If it's installed, it should be working!

**Comment by Synzvato** [comment]
@Huluti Thanks for sharing your ideas! Please see issue #18, as it's pretty much the same request.
