### ISSUE TITLE
Allow users to disable the local injections counter

### ISSUE THREAD

**Issue by ekaris** [Synzvato/decentraleyes#107]
Add a checkbox to disable the counter

**Comment by fastcopy** [comment]
+1! There's no need to write this information to the file(I want to reduce DISK IO). Also, disabing it will enhance privacy.

**Comment by Synzvato** [comment]
@fastcopy When you directly edit your preferences in ```about:config```, the settings file ```prefs.js``` is updated immediately. However, updating any settings with simple-prefs (used by the injection counter) does not result in direct disk writes. Changes are saved once, when you close your browser.

**Comment by ekaris** [comment]
If one doesn't need the count its still a useless feature for us that we should be able to disable

**Comment by Synzvato** [comment]
@ekaris Thanks for sharing your views on the matter.
