### ISSUE TITLE
Paths of local cache for whitelisting?

### ISSUE THREAD

**Issue by kittenarmy** [Synzvato/decentraleyes#109]
Where are the cached files stored? I'm concerned decentraleyes cache will be deleted by system cleaning software such as CCleaner. 

Also, does this cache persist after clearing browser history within Firefox?

**Comment by Gitoffthelawn** [comment]
They are currently stored within the extension itself.  System cleaning software and cleaning browser history will not harm anything in Decentraleyes.

**Comment by kittenarmy** [comment]
@Gitoffthelawn, thanks! Extension is jid1-BoFifL9Vbdl2zQ@jetpack.xpi
