### ISSUE TITLE
Remove referer field from requests to not-mirrored CDN libraries

### ISSUE THREAD

**Issue by ssauce** [Synzvato/decentraleyes#11]
In situations where the requested CDN library is not mirrored to avoid bloating the add-on, remove the referer field to improve the user's privacy.

**Comment by Synzvato** [comment]
Great thinking, but I'm glad to say that this has already been implemented. If Decentraleyes detects a valid CDN request, it immediately erases its "Referer" header.

Code: https://github.com/Synzvato/decentraleyes/blob/5b272abb0360e6dfee655bbc57ca390e2bc16c1d/lib/interceptor.js#L64

**Comment by ssauce** [comment]
Ah, I didn't realise it was already implemented. Maybe this feature should be written in the readme or in Mozilla website addon description? Or is it already and I missed it?
Thanks for the addon btw :)

**Comment by Synzvato** [comment]
You're absolutely right. Currently, it's only ever mentioned in an older [changelog](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/versions/?page=1#version-1.1.3) and I agree with you that this deserves a more prominent spot. I did not realize it had gotten snowed under and have added it to the Frequently Asked Questions section on the add-on's [download page](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes).

My pleasure, thanks a lot for contributing!
