### ISSUE TITLE
Add jQuery 1.9.1 and jPlayer to the default bundle

### ISSUE THREAD

**Issue by ghost** [Synzvato/decentraleyes#110]
http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
jquery.jplayer.min.js

**Comment by fastcopy** [comment]
> 
> <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
> <script type="text/javascript" src="js/jquery.jplayer.min.js"></script>
>

**Comment by fastcopy** [comment]
fuck github... why my post disappear...


http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
jquery.jplayer.min.js

**Comment by Synzvato** [comment]
Thanks for your request!

I'm happy to say that ```jQuery 1.9.1``` is already part of the default bundle. However, ```jPlayer``` is not currently included. This has a lot to do with the fact that we use library usage statistics by W3Techs when deciding on what to include. The ```jPlayer``` plug-in does not have a large enough market share.
