### ISSUE TITLE
Integrate seamlessly with other content blockers

### ISSUE THREAD

**Issue by robinpaulson** [Synzvato/decentraleyes#111]
Would it be possible for decentraleyes to automatically whitelist sites in noscript, the sites which are included in decentraleyes' local cache that is? I see in your wiki you ask users to manually whitelist sites such as ajax.googleapis.com, it would be nice if this could happen automatically.

https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#why-doesnt-it-deliver-resources-from-cdns-i-block-using-a-different-add-on

Sorry if it already does this, I had trouble understanding the second half of that FAQ entry.

**Comment by KOLANICH** [comment]
Why not to integrate it into umatrix? I mean eliminate it as a separate addon and add an additional tab into umatrix.

**Comment by robinpaulson** [comment]
I suppose it could be integrated into many add-ons, including your example and noscript, etc.

**Comment by Synzvato** [comment]
@robinpaulson Thanks for your feedback on the FAQ entry! Decentraleyes does not automatically whitelist resources within other add-ons for privacy and security reasons. It already integrates seamlessly, in the sense that it acts as a last layer of defense for requests that you would normally need to allow.
