### ISSUE TITLE
Testing page not working

### ISSUE THREAD

**Issue by 9Morello** [Synzvato/decentraleyes#116]
I'm getting error 502 when trying to access https://decentraleyes.org/test.

**Comment by RoxKilly** [comment]
The whole domain `decentraleyes.org` is down. Maybe the author @Synzvato  has lost interest in the project?

**Comment by 9Morello** [comment]
Yeah, it seems the project is dead. Thats sad, I don't know about any similar add-on.

**Comment by Gitoffthelawn** [comment]
@9Morello I doubt the project is dead.  Here are some other possibilities:

Thomas (Synzvato)
  1. Is on vacation.
  1. Is busy with other projects.
  1. Is ill.
  1. Has a loved one with an emergency.
  1. Wanted to take a break.
  1. Was abducted by intergalactic aliens.  They will return him to our little planet once probing is complete.

The project is completely open source, so as long as you follow [the license](https://www.mozilla.org/MPL/2.0/), you can fork it and make any changes you like.

I've been tempted to create a fork that contains more libraries, but I've been too busy to do so.

**Comment by Synzvato** [comment]
@Gitoffthelawn Thanks for jumping in! I can confirm that the project is definitely not dead and that we're slowly gearing up for a full ```WebExtension``` rewrite. I've been unavailable for the past few weeks and will be mostly unavailable next week as well. I will take a look at the website as soon as possible!

**Comment by Gitoffthelawn** [comment]
@Synzvato You're welcome.  I know you've put quite a bit of work into this project, and figured you just need a little personal time to spend on other priorities.

The `WebExtensions` rewrite is something to appreciate in the future.  Thanks!

**Comment by Synzvato** [comment]
The [testing utility](https://decentraleyes.org/test) should be back online.
