### ISSUE TITLE
Decentraleyes breaks Yandex Disk

### ISSUE THREAD

**Issue by dartraiden** [Synzvato/decentraleyes#117]
Example URL: https://yadi.sk/d/buEC80xBsqe4F/15.6%20-%202010.03.01
Download button don't work with Decentraleyes enabled

**Comment by Feodor2** [comment]
It also breaks mail.yandex.ru. It is something with yastatic.net, apparently they changed js files there.
How one can see what files is using. I do know fiddler, but since for some time it incompatible with new type https connections.

**Comment by Feodor2** [comment]
I managed to make fiddler work. Yandex wants jquery 1.11.0
There is something with jquery substitution, it does not happen.

**Comment by Atavic** [comment]
The link in the source has a string:
`/Gksoiw7sCWKl3P7-dP1d4Assx6YQzFL2hEyhZJ4tI-M=:/`

This part of the link disappears once you click on it and look at the Browser URL.

**Comment by Synzvato** [comment]
@dartraiden Thanks for reporting this! It's a known problem (see issue #16). It's a browser limitation that Mozilla is currently looking into. This should be fixed after we port the add-on to ```WebExtensions```.

In the meantime, please try adding ```yadi.sk``` to your Decentraleyes domain whitelist.

**Comment by dimqua** [comment]
@Synzvato this bug still affect version 2.0.

**Comment by Synzvato** [comment]
@dimqua Thanks for reporting this regression! Expect the very next update to fix the issue.
