### ISSUE TITLE
How can I exclude domains from inspections?

### ISSUE THREAD

**Issue by jorg35** [Synzvato/decentraleyes#118]
Please help how to disable domain analysis. how to add a domain to the white-list

**Comment by Synzvato** [comment]
@jorg35 To add a domain to the whitelist, navigate to ```about:addons```, go to Decentraleyes, Preferences, and then add the domain to "Exclude Domains from Inspections". 

Hope it helps. Also, please consider updating your add-on review if it does. Thanks!

**Comment by jorg35** [comment]
Thanks.

**Comment by Synzvato** [comment]
@jorg35 That's curious. In what cases (or for what domains) doesn't it work well?

**Comment by userneu** [comment]
Hi. Synzvato, can you give an example of whitelisting? What format should I use? Thanks.

**Comment by Synzvato** [comment]
@userneu If you would like to add both ```example.com``` and ```example.org``` to your whitelist, the following entry would do the trick: ```example.com;example.org```. No spaces, and ```;``` as a separator. Good luck!

**Comment by userneu** [comment]
`mail.yandex.ru` is not working with decentraleyes. I tried to add `yandex.ru` and `mail.yandex.ru` but with no result.  What am I doing wrong?

**Comment by Synzvato** [comment]
@userneu Does disabling Decentraleyes fix the issue for you? I'm asking, because I'm also seeing an error in my browser console, and mine appears to be unrelated to Decentraleyes.

**Comment by userneu** [comment]
@Synzvato Yes. Disabling fixes the problem.

**Comment by Synzvato** [comment]
@userneu What I suspect is that you're using an extension that strips ```Referer```-headers from requests, and that you have _"Block requests for missing resources"_ set to ```true```. If you could send me an email, we can take a closer look at your particular environment. Perhaps we can cook up a tailored solution.

**Comment by userneu** [comment]
@Synzvato 
Hi again.
I have fount culprit. Its pref called `network.http.referer.spoofSource`. If set to `true` then the above-described issues happen.

**Comment by Synzvato** [comment]
@jorg35 I'm happy to say that the upcoming ```v2.0.0``` release will make domain whitelisting easier, and more reliable. It will peek at the domain in the corresponding tab when making its decision, instead of the domain of the page or frame that is making the request. It will also feature related UI-improvements.
