### ISSUE TITLE
The latest release is incompatible with Pale Moon 27

### ISSUE THREAD

**Issue by beerisgood** [Synzvato/decentraleyes#119]
First, thanks for your addon and for Pale Moon support!

Unfortunately your addon doesn't work with Pale Moon 27. I can open the option window and it can be installed but it doesn't work - testet with your testsite.

Pale Moon 27 is currently in alpha stage but if you can get it work again, then that would be awesome!
Here you can get the new version: https://www.palemoon.org/WIP/

Ah the reason is probably your addon is a jetpack addon, right? Pale Moon 27+ doesn't support Jetpack addons.

**Comment by beerisgood** [comment]
Pale Moon goes now to beta 1 and your addon is marked as incompatible because of Jetpack.
Can you please build your addon without Jetpack?

**Comment by xbeyond1** [comment]
It'd be awesome to continue getting this addon with the next milestone of Pale Moon as well. Are you continuing to support it?

**Comment by CyanogenMod2** [comment]
Hello :)  ty 4 your efforts...  I too look forward to a 27 version.  thanks

**Comment by sergeevabc** [comment]
+1

**Comment by Synzvato** [comment]
Thanks for letting me know you are interested in continued Pale Moon support. I'm trying my best to keep Decentraleyes running on Pale Moon, but it is becoming increasingly hard for me to keep it compatible.

Pale Moon is moving away from ```Jetpack```, and Firefox is moving away from ```XPCOM/XUL```. I'm currently porting Decentraleyes to ```WebExtensions``` to keep it compatible with future versions of Firefox. A new Pale Moon version of Decentraleyes would need to be a completely separate ```XPCOM/XUL``` add-on.

Personally, I lack the time and resources to maintain a Pale Moon fork. I would, however, be happy to support official Pale Moon builds and work together with anyone who would like to help out. I will also see if it's possible for me to roll out a (minimum viable) Pale Moon 27 compatible release.

**Comment by beerisgood** [comment]
*bump*

The last version for Pale Moon you provide is 1.3.5 but the latest is 1.3.7
I hope you support Pale Moon.
