### ISSUE TITLE
Add support for e10s multi-process Firefox

### ISSUE THREAD

**Issue by maximus5959** [Synzvato/decentraleyes#121]
https://wiki.mozilla.org/Electrolysis

https://arewee10syet.com/

**Comment by zer09** [comment]
@Synzvato is there a change implementing ff e10s for this add-on?

**Comment by Lcstyle** [comment]
I am also looking for this....

the firefox compatibility reporter is reporting this plugin as not supporting multiprocess

https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/?src=api

**Comment by dralley** [comment]
Since this addon isn't that big in terms of code, it might be the case that the best solution for this is to just port the code to the WebExtensions API (provided it is sufficiently featured at this point to do so).

e10s support would come for "free", and the WebExtensions transition will have to happen at some point anyway.

**Comment by OdinGitDat** [comment]
I am running decentraleyes on e10s enabled firefox and I don't notice any slowing down or instabilities. Extension also works fine according to the testing utility.

**Comment by TriMoon** [comment]
I can confirm the [testing utility](https://decentraleyes.org/test) shows all is OK 👍
  - using latest "FF Developer Edition" with e10s enabled.
  - Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0 ID:20161020004015 CSet: 95567c6551ea7dfef517e7b3f50fe0be209a3a2a

**Comment by dralley** [comment]
@Synzvato Perhaps this means you can check the flag marking it e10s compatible?

**Comment by Synzvato** [comment]
@TriMoon @OdinGitDat Thanks for running some tests and letting me know, appreciated!

@dralley Yes, since the add-on seems to be functional with ```e10s``` enabled, I think it's safe to say that we can mark it ```e10s``` compatible. A ```WebExtensions``` port is in the works, though.

**Comment by Synzvato** [comment]
There's one more thing I need to know before I can mark this as being ```e10s``` compatible. Were these tests performed with shims disabled? If not, then the add-on might be incompatible despite appearing to be ready for ```e10s```. For more information on testing with shims disabled, have a look at [this page](https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Multiprocess_Firefox_and_the_SDK).

**Comment by sergeevabc** [comment]
By the way, e10s [might be overrated](https://forum.palemoon.org/viewtopic.php?t=6660) actually.

**Comment by dralley** [comment]
@sergeevabc Completely disagree, there are a great deal of benefits

* Trivial to port Chrome extensions over to Firefox
* Designed with multiprocess (e10s) in mind.  Pale Moon doesn't care about this because they're never going to use multiprocess, but Firefox is moving forward with e10s so this is important
* XUL/XPCOM is a massive legacy mess

**Comment by OdinGitDat** [comment]
@Synzvato Could you release a version of this extention with the "multiprocess" permission in the package.json? Then we can install that and try without shims.

**Comment by Bisaloo** [comment]
Seems to work fine with shim disabled according to the testing page and some quick browsing.

**Although I do not advise using a version not compiled by yourself or @Synzvato for obvious security reasons**, you can download the `xpi` here (it's zipped because github doesn't accept `xpi` files):

[decentraleyes.xpi.zip](https://github.com/Synzvato/decentraleyes/files/549945/decentraleyes.xpi.zip)

**Comment by gitarra** [comment]
I just built the addon with shims disabled.

I can confirm the basic functionality works after testing with:

- The web testing utility
- Browsing to a website containing an included jquery script and confirming that it is served locally by checking the script for the "served by decentraleyes" comment and checking with the developer tools that there was no request made to an external server.

Looking forward for the WebExtension! 👍

**Comment by Synzvato** [comment]
@OdinGitDat I'm afraid I cannot officially release an untested version with shims disabled. However, if you know how to install and run unsigned add-ons inside of your browser, you could manually tweak the ```package.json``` file by performing the steps below. I recommend reverting all of this when done.

1. Download v1.3.5 of the add-on _(right click the download button, save the target)_.
2. Open the downloaded ```.xpi``` archive using your favorite archive manager.
3. Use a text editor to open the ```package.json```, and add the multi-process permission.
4. Install and start using your custom, unsigned, copy inside of your web browser.

@Bisaloo Thanks for jumping in, and for testing ```e10s``` compatibility with shims disabled!

**Comment by OdinGitDat** [comment]
Ah yes I did try that before, but firefox said the addon was corrupted when I tried to install it. Anyway it seems to work as reported by other people so I think you're good. Bedankt ;)

**Comment by gitarra** [comment]
Dont you actually have to build the addon again with shims disabled using JPM?

Correct me if I'm wrong but from what I've understood editing the package.json isnt enough, after this you need to build the addon with JPM as the multiprocess permission in package.json gives instructions for jpm to include the correct flag in install.rdf which then is read by Firefox during the addons installation.

Maybe adding the flag manually to install.rdf would be enough unless theres also some other voodoo done by jpm.

**Comment by Synzvato** [comment]
Multi-process support has been added. However, I am unable to release the ```l10s``` update (or any future updates), because new AMO submission rules are blocking my submissions. Please see #129.

**Comment by Synzvato** [comment]
Good news. The ```l10s``` update (v1.3.6) has since been approved and is now available.
