### ISSUE TITLE
Can Decentraleyes work with web fonts?

### ISSUE THREAD

**Issue by 9Morello** [Synzvato/decentraleyes#132]
I think title says it all. Could support be added for web fonts?

**Comment by Bisaloo** [comment]
See https://github.com/Synzvato/decentraleyes/issues/105 and https://github.com/Synzvato/decentraleyes/issues/77

**Comment by 9Morello** [comment]
@Bisaloo oh, my bad for not looking. Thanks.

**Comment by Synzvato** [comment]
For administrative purposes, I'm marking this as a duplicate of #69.
