### ISSUE TITLE
Will you be compatible with Firefox 57 and beyond?

### ISSUE THREAD

**Issue by theres-waldo** [Synzvato/decentraleyes#134]
Mozilla recently [announced](https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/) that starting in Firefox 57, Firefox will no longer support addons that are not WebExtensions.

Are there plans to convert Decentraleyes to be a WebExtension, so it can continue working in Firefox 57 and beyond?

**Comment by 9Morello** [comment]
I think the author is working on it. According to a post from him in other issue, he plans to release the next version for Chromium-based browsers too.

**Comment by techdudepro** [comment]
This add-on is essentially the same as Decentraleyes... A fork of this would help with development?

https://github.com/james-fray/local-cdn

**Comment by Synzvato** [comment]
@techdudepro Many thanks for the relevant suggestion.

That extension pretty much _is_ Decentraleyes (as in, a wrapper around our core logic). The problem, however, is that the implementation in question does not allow the use of sanitized copies of the bundled resources. I would not recommend using the solution, as there are various [security implications](https://github.com/mozilla/addons-linter/issues/1035#issuecomment-258878823).

**Comment by Synzvato** [comment]
@theres-waldo Converting this extension to WebExtensions is currently top priority. However, it's highly important that the result is secure, and does not expose users to other types of hazards. Especially since this is a "Privacy and Security" extension. To make this happen, we're [discussing](https://github.com/mozilla/addons-linter/issues/1035#issuecomment-258878823) new security APIs.

**Comment by 9Morello** [comment]
I want to thank @techdudepro for showing us that fork, and @Synzvato for showing he is alive.

**Comment by Synzvato** [comment]
@theres-waldo Hi again. I'd like to give you a quick update on the situation. The new ```WebExtensions``` add-on port is starting to take shape, and its logic can be found within the ```experimental``` Git branch. The code is already successfully powering the new Chromium and Opera releases. We will get there!

**Comment by theres-waldo** [comment]
Cool, thanks for the update!
