### ISSUE TITLE
Can parts of Android Police be injected locally?

### ISSUE THREAD

**Issue by jawz101** [Synzvato/decentraleyes#138]
http://www.androidpolice.com/2017/01/02/27-new-and-notable-android-games-from-the-last-2-weeks-122016-1217/

even with NoScript, Decentraleyes, Load From Cache, Privacy Badger, and maybe a few other add-ons it's still a 34 MB download to just open this web page.

Are some of the YouTube javascript's able to be Decentraleyes'd?

**Comment by Synzvato** [comment]
As far as I can tell, the resources that are being, repeatedly, loaded into that page are unversioned. This means that they can change at any time, without prior notice. Therefore, they are hard to bundle.

Luckily, most websites are not this badly out of control. I would personally just block most of the third parties (e.g. ```chart.googleapis.com```, ```disquscdn.com```, ```gravatar.com```, ```outbrain.com```, ```pushbullet.com```, and ```youtube.com```) for said page. The result might be just as, if not more, usable. I hope this helps!
