### ISSUE TITLE
Log activity to the console

### ISSUE THREAD

**Issue by RoxKilly** [Synzvato/decentraleyes#14]
Do you think it would be a good idea, when a request is intercepted, or intercepted and served from a local resource, to log that activity to the browser console? (Ctrl+Shift+J in Firefox)

**Comment by Synzvato** [comment]
That's an interesting idea. However, based on a first look at this, I'm not getting the impression that it's encouraged or well supported (for non-debugging purposes). Mozilla appears to be pushing add-on developers towards other means such as [panels](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/panel) and [desktop notifications](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/notifications).

Combining those two elements could work, if we let users configure them, don't you think?

**Comment by RoxKilly** [comment]
I suggested logging to the console because the addon has no UI that I can see so it's difficult to tell what effect it has on a page; logging is a quick fix to this.  You're right though; if Mozilla discourages the practice, it is probably best to use panels.  Plus, panels would be accessible even to users who are not technically savvy enough to open dev tools and investigate.

**Comment by Synzvato** [comment]
> You're right though; if Mozilla discourages the practice, it is probably best to use panels.

True. I really like your idea though. But, as far as I can tell, you would have to determine the window that made the request (a tad tricky), and then execute ```console.log();``` within its document child.

> Plus, panels would be accessible even to users who are not technically savvy enough to open dev tools and investigate.

Yes, I agree. With the added risk that they might get annoying if they're not easy to configure. So it will take some work to get it right. Suggestions are welcome!
