### ISSUE TITLE
Does this work alongside granular content blockers?

### ISSUE THREAD

**Issue by rekixex** [Synzvato/decentraleyes#142]
From documentation:

> If you're using uMatrix, Edit in and Commit these lines to My rules in the Dashboard:
> 
> ```
> * ajax.aspnetcdn.com script allow
> * ajax.googleapis.com script allow
> * ajax.microsoft.com script allow
> * cdn.jsdelivr.net script allow
> * cdnjs.cloudflare.com script allow
> * code.jquery.com script allow
> * lib.sinaapp.com script allow
> * libs.baidu.com script allow
> * upcdn.b0.upaiyun.com script allow
> * yandex.st script allow
> * yastatic.net script allow
> ```

I use NoScript and uMatrix to block scripts (and everything else 3rd party with uMatrix). I tend to allow scripts on a per-site basis, not globally, because that offers better protection and is usually enough for the very basic site functionality.

Will Decentraleyes work correctly if I allow scripts with NoScript and uMatrix only on a per-site basis (without setting global rules in uMatrix like it is suggested in documentation)? In other words, will Decentraleyes work correctly out-of-the-box in combination with NoScript and uMatrix?

**Comment by Synzvato** [comment]
Hi @rekixex, and many thanks for getting in touch!

> Will Decentraleyes work correctly if I allow scripts with NoScript and uMatrix only on a per-site basis (without setting global rules in uMatrix like it is suggested in documentation)?

Absolutely. Decentraleyes acts as a last line of defense, and will not inject resources that are blocked by any other type of add-on. There's no need for global whitelists, and your strategy should work.

**Comment by rekixex** [comment]
Hi @Synzvato and many thanks for this addon! The overall idea is great. I wish you even more success with **Decentraleyes** in the future. Cheers. :)

**Comment by rekixex** [comment]
Hi @Synzvato and many thanks for this addon! The overall idea is great. I wish you even more success with **Decentraleyes** in the future. Cheers! :)

**Comment by rekixex** [comment]
Hi @Synzvato and many thanks for this addon. The overall idea is great. I wish you even more success with **Decentraleyes** in the future. Cheers. :)

**Comment by rekixex** [comment]
Hi @Synzvato and many thanks for this addon, the overall idea is great. I wish you even more success with **Decentraleyes** in the future. Cheers. :)

**Comment by rekixex** [comment]
Hi @Synzvato and many thanks for this addon, the overall idea is great. I wish you even more success with **Decentraleyes** in the future. Cheers! :)
