### ISSUE TITLE
Notify uMatrix users when blocking rules change

### ISSUE THREAD

**Issue by atomGit** [Synzvato/decentraleyes#151]
i keep the [FAQ page](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#why-doesnt-it-deliver-resources-from-cdns-i-block-using-a-different-add-on) bookmarked so i can check it for changes to the uMatrix rules when decentraleyes is updated, but this made easier if decentraleyes notified users with a link to the page after it's updated - possibilities...

* detect uMatrix and, if rules changed, offer to open FAQ page
* detect uMatrix and open FAQ page
* offer to open FAQ page after an update

**Comment by Synzvato** [comment]
Thanks for sharing your workflow! Since the add-on does not collect any data of any kind, these sorts of insights are quite valuable. I'm not sure if the ```WebExtensions``` APIs allow add-ons to collect data on other installed extensions. I will look into the possibilities, and will get back to you once I know more.

**Comment by Synzvato** [comment]
Hi again @atomGit, and thank you for your patience!

Even with today's ```WebExtension``` features, detecting uMatrix is not a viable option. If an extension update works better after changes to your uMatrix whitelist, it will surely be mentioned in the release notes.

I hope this is at least somewhat of a helpful solution. If not, could a static webpage (or a basic ```RSS``` feed) perhaps be an idea? Please re-open the issue if you're interested in any of the suggestions.

**Comment by atomGit** [comment]
well, all i'm suggesting is that it's pretty vital that users are aware that if they have uMatrix installed, Decentraleyes will not work unless they add those rules.  i'm thinking here of maybe someone that failed to read the full descrip of D-eyes, or perhaps someone who installs D-eyes first and uM sometime later and forgets about applying the rules

i think there should at least be a mention of this, even if uM can't be detected, after D-eyes is installed and after every update - like a webpage that is opened which contains this info and updated rules or whatever

thanks though! glad to see you still working on this ext. :)

**Comment by Synzvato** [comment]
> well, all i'm suggesting is that it's pretty vital that users are aware that if they have uMatrix installed, Decentraleyes will not work unless they add those rules.

In essence, Decentraleyes will work. What will likely happen is that when a certain page breaks, the user will start fiddling around with the page specific uMatrix policies. Once the user gets around to tinkering with the domain of a supported CDN, Decentraleyes will attempt to inject the dependencies locally.

The rules are meant to save users of uMatrix a bit of manual labor. By allowing all requests to known CDNs by default, and blocking requests for missing resources from inside Decentraleyes, you allow this extension to _automatically_ attempt to inject local resources, but still prevent any outgoing requests.

> i think there should at least be a mention of this, [...] after D-eyes is installed and after every update - like a webpage [...] which contains this info and updated rules or whatever

I'll definitely keep this in mind going forward! I'm still brainstorming on how to present any release notes to users from ```v2.0.0``` onwards. The recently implemented ```GUI``` increases the possibilities.

> thanks though! glad to see you still working on this ext. :)

My pleasure, and thanks for getting back to me on this, much appreciated!

**Comment by kuremu** [comment]
Could relevant ublock/matrix rules be published somewhere as a text file, so that users can just add them to their filter lists? Could even just be a raw text file here on github.
