### ISSUE TITLE
[Chrome] Options Button Displays As ï€“

### ISSUE THREAD

**Issue by war59312** [Synzvato/decentraleyes#152]
Hi,

Chrome Version 58.0.3029.13 dev (64-bit), the Popup shows Options button as:

`ï€“`

Whoops!

Thanks,

Will

**Comment by Synzvato** [comment]
@war59312 Thanks for reporting the display issues. Appreciated! As an initial fix, I have replaced the cog icon with text. Soon though, I'll bundle some font icons. That's when the cog will resurface.

**Comment by war59312** [comment]
Thanks for fixing so quickly. 👍
