### ISSUE TITLE
chrome canary: cdnjs.com is broken

### ISSUE THREAD

**Issue by publicarray** [Synzvato/decentraleyes#155]
**Edit:** I'm using chrome canary (59.0.3053.3) It seems the problem is not in latest stable so it could be a bug in chrome...

The search is broken and it is impossible to copy the code snippets from say https://cdnjs.com/libraries/jquery. usually there is a button on hover.

I think it has to do with the CSP blocking jquery.

![js console](https://cloud.githubusercontent.com/assets/5497998/24386867/3480df1e-13b5-11e7-81d8-38afc61379c0.png)

I tried adding `cdnjs.com` to the whitelist but it did not help.

![settings](https://cloud.githubusercontent.com/assets/5497998/24386930/77dde5cc-13b5-11e7-83a0-23b1d8c1c2dc.png)

**Comment by Synzvato** [comment]
Hi @publicarray and thanks for sharing your findings!

I have tried to reproduce your issue by installing Chrome Canary inside of a Windows environment (as it's Windows-only). However, despite my best efforts, I was unable to break the page in question.

![test-results](https://cloud.githubusercontent.com/assets/2366020/24420129/02ceeac8-13f2-11e7-8265-69bbebfe42f9.png)

As shown above, I was using ```v59.0.3054.0``` as opposed to ```v59.0.3053.3```. The version of Decentraleyes used, was ```v1.3.7.4```. Could you please try upgrading to the currently most recent Canary build?

**Comment by publicarray** [comment]
Thanks for looking into this. I have updated Canary, still no dice. I suspect it my have to do with feature flags. `chrome://flags`. I'll investigate and get back to you. 

PS Carary is mac/win.

**Comment by publicarray** [comment]
Ah found it `chrome://flags/#enable-experimental-web-platform-features`. I suppose this is a chrome/website specific issue. Disabling the extension temporarily or disabling the flag temporarily fixes the issue.

**Comment by Synzvato** [comment]
> PS Carary is mac/win.

You're absolutely right. What I meant to say was that Canary-builds are not available for Linux.

> Ah found it [...]. I suppose this is a chrome/website specific issue. Disabling the extension temporarily or disabling the flag temporarily fixes the issue.

I'm happy to hear you managed to track down the issue. I'll attempt to find out what experimental web platform feature is at fault here. I think extensions should be allowed to override CSPs.
