### ISSUE TITLE
Make disabling network prediction services optional

### ISSUE THREAD

**Issue by chrcoluk** [Synzvato/decentraleyes#157]
The extension forcefully turns of page prediction (dns prefetching), can you please make this optional as I can feel the performance hit of waiting for initial dns lookups.

**Comment by Synzvato** [comment]
Hi @chrcoluk. Thanks for getting in touch!

I'm afraid Chrome's _"Use a prediction service to load pages more quickly"_ feature goes a lot further than looking up DNS records. It pre-renders sites, and preemptively opens up TCP and SSL connections.

This means that Google's prediction service will be able to contact Content Delivery Networks outside of the context of your active tab. When it does, Decentraleyes will not be able to intercept the request.

With this in mind, would you still like to manually enable the pre-fetching feature?

_Source: https://developer.chrome.com/extensions/privacy_

**Comment by dkudriavtsev** [comment]
Yes

**Comment by chrcoluk** [comment]
yes please, I accept your explanation but having the choice is king.

**Comment by dkudriavtsev** [comment]
Hmmm. Is there a way to have a local HTTP server in a Chrome extension?
