### ISSUE TITLE
The Chromium extension breaks GitHub for me

### ISSUE THREAD

**Issue by jmfgdev** [Synzvato/decentraleyes#158]
Decentraleyes + Chromium on 64bit GNU/Linux latest Chromium build and Decentraleyes

forking and invites don't work with Decentraleyes, both works immediately when turned off.

**Comment by Synzvato** [comment]
Hi @jmfgdev, and thanks for sharing your concerns! However, I am unable to reproduce your issue, as I am able to invite collaborators to projects with Decentraleyes ```v1.3.7.4``` enabled (on x64 GNU/Linux).

GitHub does not rely on any big third party CDNs, so the add-on should not even be interfering. I am unsure as to why you are having these problems on your end. Could you please share some additional details?

**Comment by jmfgdev** [comment]
Hmm, I would like to share more details but it really is that simple. I had the latest Chromium and Decentraleyes and as soon as I removed Decentraleyes, certain features of GitHub began to work again.

**Comment by Synzvato** [comment]
@jmfgdev I'm not able to reproduce your problems, but I'll be sure to leave this issue ```open``` for at least another week, to allow others to weigh in. If this happens to others as well, they'll likely end up here.

In any case, you could try adding  ```github.com``` to Decentraleyes' domain whitelist.
