### ISSUE TITLE
Decentraleyes does not locally inject MathJax

### ISSUE THREAD

**Issue by rawuUuUuUuUul-GOAAAAAAAAAAAAL** [Synzvato/decentraleyes#159]
Test url: https://cs.stackexchange.com/

**Comment by Synzvato** [comment]
Hi @rawuUuUuUuUul-GOAAAAAAAAAAAAL, and thanks for getting in touch.

The extension comes with a collection of the most commonly used versions of resources (based on [web crawling statistics](https://github.com/Synzvato/decentraleyes/issues/7#issuecomment-161157495)). Adding all available CDN resources to the add-on is simply not feasible.

> Bundled Resources: AngularJS, Backbone.js, Dojo, Ember.js, Ext Core, jQuery, jQuery UI, Modernizr, MooTools, Prototype, Scriptaculous, SWFObject, Underscore.js, and Web Font Loader.

_Source: The full add-on descriptions for Firefox [[1](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/)] and Chromium [[2](https://chrome.google.com/webstore/detail/decentraleyes/ldpochfccmkkmhdbclfhpagapcfdljkj)]._

**Comment by rawuUuUuUuUul-GOAAAAAAAAAAAAL** [comment]
Hi @Synzvato 

Thanks for the precision. I got confused at first since I saw `CDNJS (Cloudflare)` and thought you bundled some resources they offer.

While Mathjax has a lot of users ([179 Million monthly users](https://www.mathjax.org/cdn-shutting-down/)) I understand that it may not be considered as commonly used as other CDN resources and thus should not be included.

**Comment by 5hynycms52tac** [comment]
@Synzvato W3Techs started collecting stats for MathJax, you may want to follow them ;) https://w3techs.com/technologies/overview/javascript_library/all https://w3techs.com/technologies/details/js-mathjax/all/all
