### ISSUE TITLE
breaks trends.google.com

### ISSUE THREAD

**Issue by atomGit** [Synzvato/decentraleyes#160]
trends.google.com loads a blank page

DC 1.3.8
FF 53
Linux

**Comment by Bisaloo** [comment]
It works fine for me with the same setup.

**Comment by atomGit** [comment]
there is a console error with DC enabled that is not there when the extension is disabled - the page won't load for me with DC enabled

`GET 
https://trends.google.com/trends/ [HTTP/1.1 200 OK 127ms]
GET 
https://fonts.googleapis.com/css [HTTP/1.1 200 OK 0ms]
GET 
https://fonts.googleapis.com/css [HTTP/1.1 200 OK 0ms]
GET 
https://ssl.gstatic.com/trends_nrtr/981_RC01/css_bin.css [HTTP/1.1 200 OK 0ms]
GET 
https://www.gstatic.com/charts/loader.js [HTTP/1.1 200 OK 0ms]
GET 
https://ssl.gstatic.com/trends_nrtr/981_RC01/third_parties_min.js [HTTP/1.1 200 OK 0ms]
GET 
https://www.google.com/insights/consumersurveys/async_survey [HTTP/1.1 200 OK 0ms]
GET 
https://ssl.gstatic.com/trends_nrtr/981_RC01/trends.js [HTTP/1.1 200 OK 0ms]
GET 
https://www.gstatic.com/og/_/js/k=og.og.en_US.o-SyWnQPMWo.O/rt=j/m=ld,gl,is,id,nb,nw,sb,sd,p,vd,awd,st,lod,eld,ip,dp,cpd/exm=bt,base,bn,bu,cp,el,lo,sbi,ni,sf,up,dd,aw,iw,if,gi,vi,pi,eq,uc/d=1/ed=1/rs=AA2YrTvXNEBpxbRAgPPkt3kcmxXPUZuTJQ [HTTP/1.1 200 OK 0ms]
Error: [$injector:modulerr] http://errors.angularjs.org/1.5.12-local+sha.7f65bbb8d/$injector/modulerr?p0=trendsApp&p1=%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.5.12-local%2Bsha.7f65bbb8d%2F%24injector%2Fmodulerr%3Fp0%3DngMaterial%26p1%3D%255B%2524injector%253Anomod%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.5.12-local%252Bsha.7f65bbb8d%252F%2524injector%252Fnomod%253Fp0%253DngMaterial%250AN%252F%253C%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4619%253A433%250AAe%252F%253C%252F%253C%252F%253C%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4637%253A337%250Ab%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4636%253A395%250AAe%252F%253C%252F%253C%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4637%253A122%250Ag%252F%253C%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4649%253A17%250Aq%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4620%253A369%250Ag%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4648%253A382%250Ag%252F%253C%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4649%253A34%250Aq%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4620%253A369%250Ag%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4648%253A382%250Agb%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4652%253A382%250Ad%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4634%253A19%250ALc%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4634%253A332%250Ave%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4633%253A1%250A%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4935%253A253%250Ab%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4801%253A193%250AJe%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4646%253A187%250Ac%2540https%253A%252F%252Fssl.gstatic.com%252Ftrends_nrtr%252F981_RC01%252Fthird_parties_min.js%253A4646%253A136%250A%0AN%2F%3C%40https%3A%2F%2Fssl.gstatic.com%2Ftrends_nrtr%2F981_RC01%2Fthird_parties_min.js%3A4619%3A433%0Ag%2F%3C%40https%3A%2F%2Fssl.gstatic.com%2Ftrends_nrtr%2F981_RC01%2Fthird_parties_min.js%3A4649%3A292%0Aq%40https%3A%2F%2Fssl.gstatic.com%2Ftrends_nrtr%2F981_RC01%2Fthird_parties_min.js%3A4620%3A369%0Ag%40https%3A%2F%2Fssl.gstatic.com%2Ftrends_nrtr%2F981_RC01%2Fthird_parties_min.js%3A4648%3A382%0Ag%2F%3C%40https%3A%2F%2Fssl.gstatic.com%2Ftrends_nrtr%2F981_RC01%2Fthird_parties_min.js%3A4649%3A34%0Aq%40https%3A%2F%2Fssl.gstatic.com%2Ftrends_nrtr%2F981_RC01%2Fthird_parties_min.js%3A4620%3A369%0Ag%40https%3A%2F%2Fssl.gstatic.com%2Ftrends_nrtr%2F981_RC01%2Fthird_parties_min.js%3A4648%3A382%0Agb%40https%3A%2F%2Fssl.gstatic.com%2Ftrends_nrtr%2F981_RC01%2Fthird_parties_min.js%3A4652%3A382%0Ad%40https%3A%2F%2Fssl.gstatic.com%2Ftrends_nrtr%2F981_RC01%2Fthird_parties_min.js%3A4634%3A19%0ALc%40https%3A%2F%2Fssl.gstatic.com%2Ftrends_nrtr%2F981_RC01%2Fthird_parties_min.js%3A4634%3A332%0Ave%40https%3A%2F%2Fssl.gstatic.com%2Ftrends_nrtr%2F981_RC01%2Fthird_parties_min.js%3A4633%3A1%0A%40https%3A%2F%2Fssl.gstatic.com%2Ftrends_nrtr%2F981_RC01%2Fthird_parties_min.js%3A4935%3A253%0Ab%40https%3A%2F%2Fssl.gstatic.com%2Ftrends_nrtr%2F981_RC01%2Fthird_parties_min.js%3A4801%3A193%0AJe%40https%3A%2F%2Fssl.gstatic.com%2Ftrends_nrtr%2F981_RC01%2Fthird_parties_min.js%3A4646%3A187%0Ac%40https%3A%2F%2Fssl.gstatic.com%2Ftrends_nrtr%2F981_RC01%2Fthird_parties_min.js%3A4646%3A136%0A  third_parties_min.js:4619:433
GET 
https://www.google.com/insights/consumersurveys/static/400727501218856442/prompt_embed_static.js [HTTP/1.1 200 OK 0ms]
GET 
https://www.google.com/insights/consumersurveys/gk/prompt [HTTP/1.1 200 OK 32ms]
GET 
https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.DTPeBB_SvOA.O/m=gapi_iframes,googleapis_client,plusone/rt=j/sv=1/d=1/ed=1/rs=AHpOoo-J3J0yqNDMPVrmQT6j-SBFfGx8oA/cb=gapi.loaded_0 [HTTP/1.1 200 OK 0ms]`

**Comment by Synzvato** [comment]
Hi @atomGit, and thanks for getting in touch! Have you tried disabling the "block requests for missing resources" preference? It blocks all traffic to supported CDNs (for all non-whitelisted websites).

**Comment by atomGit** [comment]
i totally forgot about that option - sorry :)
