### ISSUE TITLE
Make modifying request headers optional

### ISSUE THREAD

**Issue by puff-m-d** [Synzvato/decentraleyes#163]
Hello,

When using the following two extensions, Decentraleyes 1.3.7.5 and uMatrix 1.0.0, on Chromium version 60.0.3079.0 (Official Build) (64-bit), I get the following warning/error:
> Warning:
> - This extension failed to modify the request header "Referrer" of a network request because the modification conflicted with another extension (uMatrix).

I did not have this warning/error when using Decentraleyes 1.3.7.4 and uMatrix 1.0.0 on Chromium version 60.0.3079.0 (Official Build) (64-bit). It has only appeared since updating Decentraleyes to version 1.3.7.5 (with no other changes to extension or browser versions). It seems something has changed in this version where the referrer spoofing in uMatrix is not compatible.

I realize when two extensions try to do the same thing in Chrome/Chromium, the first to get to it succeeds while the other fails. Normally I guess that one would ignore this warning but I am concerned maybe this is breaking something with Decentraleyes. I would very much like to be able to use the referrer spoofing feature in uMatrix alongside Decentraleyes without the fear that something was broken and/or not working as it should.

Can anyone provide any insight into this issue?

Best regards,
Kent

**Comment by Synzvato** [comment]
Hi @puff-m-d, and thanks for getting in touch!

> I did not have this warning/error when using Decentraleyes 1.3.7.4 and uMatrix 1.0.0 on Chromium version 60.0.3079.0 [...]. It has only appeared since updating Decentraleyes [...].

This has to do with the (re)introduction of a privacy enhancing feature that removes sensitive data from CDN requests that cannot be handled locally. That's why this only affects [v1.3.7.5](https://github.com/Synzvato/decentraleyes/tree/experimental#v1375) (and higher).

> I realize when two extensions try to do the same thing in [...], the first to get to it succeeds while the other fails. Normally I guess that one would ignore this warning but I am concerned [...].

I'm happy to say that these conflicts are not breaking any functionality. However, I can imagine that these constant warning messages can become quite annoying. I will see if I can make this optional.

Thanks again, and I hope this addresses your concerns. If not, please let me know.

**Comment by puff-m-d** [comment]
Hello Synzvato,

Thanks for your reply and letting me know the issue is not breaking any functionality of either Decentraleyes or uMatrix. That was my only concern. I assume that I am losing the "privacy enhancing feature" (re)introduced into Decentraleyes but uMatrix is somehow helping to compensate for that. I only ask this as to help in an informed decision as whether to use the "privacy enhancing feature" of Decentraleyes or the "Spoof HTTP referrer string of third-party requests." of uMatrix...

You may mark this issue as "closed" if you wish as my concerns have been addressed...

**Comment by jaywk** [comment]
+1 to make both the Referer and Strict HTTPS options to be turned either on or off so that addons such as uMatrix do not overlap in functionality.

**Comment by Synzvato** [comment]
@jaywk If by "Strict HTTPS options" you mean the (```HTTP``` to ```HTTPS```) [redirection logic](https://github.com/Synzvato/decentraleyes/commit/826cfd9f72f46715608e83f7250d987a01f68cca#diff-96a6031da68c02c778b15aa31654e8c4R97), then I'm happy to say that it does not cause any overlaps. It's there to allow people to resolve existing conflicts.

**Comment by puff-m-d** [comment]
Hello,

> When using the following two extensions, Decentraleyes 1.3.7.5 and uMatrix 1.0.0, on Chromium version 60.0.3079.0 (Official Build) (64-bit), I get the following warning/error:
> > Warning:
> > This extension failed to modify the request header "Referrer" of a network request because the modification conflicted with another extension (uMatrix).

This error occurs when you are using the "Spoof HTTP referrer string of third-party requests." in uMatrix privacy settings. It can occur with either uMatrix or Decentraleyes.
![2017 06 06_12h26m05s_003_00006](https://user-images.githubusercontent.com/8797546/26840228-71718b8c-4ab3-11e7-9656-13a20dc669f9.jpg)
What I do to alleviate this issue is as follows:
- When you see the extension error occur (whether for uMatrix or Decentraleyes), click on the uMatix icon to open the matrix.
- In the top row you will see 3 vertical dots which you will click.
- Click the "Referrer spoofing" slider to turn it off for this site only.
- Click on the "Lock" icon to save.
- Note: You must be on the site where the extension error occurred.
![2017 06 06_12h17m21s_002_00005](https://user-images.githubusercontent.com/8797546/26839865-460735ba-4ab2-11e7-94f1-d27c863670ad.jpg)
When the above steps are followed, you will not get an extension error with either uMatrix or Decentraleyes  as the two extensions will not be competing to do the same thing. You should not have to do this for many sites as I have only encountered 3 that I have so far had to do this for so far.
Hope this helps...

**Comment by wiredrunner** [comment]
There should be an option to disable the referrer function

**Comment by Synzvato** [comment]
@wiredrunner I agree! Expect spoofing to become optional in a future update.
