### ISSUE TITLE
Breaks Google play links

### ISSUE THREAD

**Issue by PDXUser** [Synzvato/decentraleyes#164]
When on an app page to install or view read more links or any other link on the page, it allows for the link to be clicked but nothing happens.  

Disabling the plugin allows for it to work again.

**Comment by Synzvato** [comment]
Thanks for reporting this! I'm assuming you're using Decentraleyes for Firefox? For the time being, please add ```play.google.com``` to your local list of ignored domains (see add-on preferences).

**Comment by da2x** [comment]
The root cause of this issue is issue #170.

**Comment by Synzvato** [comment]
@da2x Have you been able to replicate this exact problem? The website works for me.

**Comment by da2x** [comment]
If I strip out the CSP header than Decentraleyes works as expected and the app-install popover starts working.

**Comment by Synzvato** [comment]
> If I strip out the CSP header [...] the app-install popover starts working.

That's pretty odd, since ```play.google.com``` depends on non-bundled content (jQuery ```v3.1.0```). As a result, the extension shouldn't interfere. I am unable to detect any ```CSP``` errors on my end.

**Comment by Synzvato** [comment]
I am unable to reproduce this problem, and no one has reported any Google Play bugs since. As a result, the issue will be closed. Anyone who is still having problems with said service is free to re-open it.
