### ISSUE TITLE
Breaks the Boomerang extension for Firefox

### ISSUE THREAD

**Issue by MacProGirl** [Synzvato/decentraleyes#165]
It breaks the following extension which is extension which gives a lot of good features to Gmail.
http://www.boomeranggmail.com/download.html

Could it be fixed or is there a workaround?

Thanks!

**Comment by imageverif** [comment]
I guess you can try as a first step to add the gmail.com in the whitelist for Decentraleyes and see if things work as expected?

**Comment by Synzvato** [comment]
Hi @MacProGirl, and thanks for getting in touch, and for reporting this. Did you receive any specific error (or warning) messages? Please share additional details if possible. Thanks again!
