### ISSUE TITLE
Would a log-free CDN be acceptable?

### ISSUE THREAD

**Issue by kxpvcr** [Synzvato/decentraleyes#169]
Hey, would you still prefer to block a CDN, if it promised to be log-free?

**Comment by ibrokemypie** [comment]
The point isnt to block but to server locally, reducing the external requests that you mujst wait for before a site loads

**Comment by Synzvato** [comment]
@kxpvcr Yes. This project aims to make you less dependent on centralized services when browsing the web. When a costly service is "free", there's usually a catch. Who would like to operate at a loss?

**Comment by TriMoon** [comment]
>  if it promised to...

The internet is full of "promises", that's why no one trusts "promises" anymore unless committed by a contract and even then it's safe to assume the "promise" will be/is violated... 😁
