### ISSUE TITLE
Freezes when used alongside Adblock Latitude

### ISSUE THREAD

**Issue by MustardTiger666** [Synzvato/decentraleyes#171]
when loading certain sites this add on completely freezes palemoon and forces me to have to close the browser and start again. about 1 in 4 sites seem to cause this issue. i understand there's probably something about those sites causing this to happen but what could it be?

**Comment by sergeevabc** [comment]
To investigate this further, issue have to be reproducible.
From your words, we know the following and this is clearly not enough:
- Browser is Palemoon (which version?)
- DecentralEyes extension is on (which version?)
- Four sites (which one?) should be opened to observe the freeze

**Comment by Synzvato** [comment]
Thanks @MustardTiger666 for your report, and thank you @sergeevabc for troubleshooting. Although there is not much information to work with, I'm fairly sure this is a duplicate of related issue #140.
