### ISSUE TITLE
Is this add-on feature complete?

### ISSUE THREAD

**Issue by jawz101** [Synzvato/decentraleyes#172]
The readme makes it sound as though it'll eventually cache a ton of stuff but... like... it doesn't sound like an idea that would take too long to go from the drawing board into development.

**Comment by Synzvato** [comment]
No, this extension is not feature complete. Certain features have been held back intentionally, because Firefox 57 demands a rewrite. Expect new features once everything has been ported over.

Thanks for sharing your concerns, and I hope this answers your question.
