### ISSUE TITLE
Decentraleyes and roboto font from google fonts

### ISSUE THREAD

**Issue by arthurlutz** [Synzvato/decentraleyes#176]
Am having a problem with my firefox (53 and nightly) which I can't find a way to fix : the roboto font (which is quite widely used) doesn't show. At some point I installed decentraleyes and I would like to rule out this addon as the source of the problem. Can you help me debug this ? I tried to deactive it, then remove the addons but my problem persists. 

It looks like this : 

https://gitlab.com/gitlab-org/gitlab-ce/issues/31389
https://askubuntu.com/questions/895214/roboto-is-invisible-in-firefox
https://bugzilla.mozilla.org/show_bug.cgi?id=1331797

**Comment by arthurlutz** [comment]
Sorry for the noise, solved it by installing fonts-roboto-* on my ubuntu...

**Comment by Synzvato** [comment]
@arthurlutz No worries, and thanks for coming back to let us know!
