### ISSUE TITLE
Some websites reject resource injections

### ISSUE THREAD

**Issue by Mitame** [Synzvato/decentraleyes#177]
[Original Issue](https://github.com/webcompat/web-bugs/issues/7161)

Some websites will refuse to load the injected resources when they don't have the `access-control-allow-origin`. One example is this website https://www.yourvotematters.co.uk/faq/voting-by-post

Console output:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://code.jquery.com/jquery-1.9.1.min.js. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 
None of the “sha256” hashes in the integrity attribute match the content of the subresource. voting-by-post
Error: Bootstrap's JavaScript requires jQuery bootstrap.min.js:6:37
Error: Bootstrap's JavaScript requires jQuery plugins.min.js:65:41
ReferenceError: jQuery is not defined[Learn More] typeahead.bundle.min.js:7:164
ReferenceError: $ is not defined[Learn More] global.min.js:45:1
```

Easiest way to fix this (I would imagine) is to just add the header ‘Access-Control-Allow-Origin: *’ in all injections but not looked at anything.

**Comment by lilydjwg** [comment]
https://www.glowing-bear.org/ breaks for the same reason too.

**Comment by mcnesium** [comment]
Wow there is one issue on this already. I only ran into this issue with decentraleyes v2.0.0 and Glowing Bear is the only application I found so far:

![bildschirmfoto 2017-10-16 um 09 50 12](https://user-images.githubusercontent.com/476060/31600758-e0205214-b257-11e7-99f4-76b3e95204d4.png)
(sorry for german screenshot)

**Comment by Synzvato** [comment]
I'm happy to say that Decentraleyes ```v2.0.1``` will not break any of the websites above. A permanent fix is in the works. I will soon be posting some updates on the progress, inside of related issue #16.

**Comment by Synzvato** [comment]
I have since decided to create a new bug ([```1419459```](https://bugzilla.mozilla.org/show_bug.cgi?id=1419459)) on Mozilla's bugtracker. Upvotes are welcome.
