### ISSUE TITLE
Fix a typographical error in the Swedish locale

### ISSUE THREAD

**Issue by ulf33286** [Synzvato/decentraleyes#178]
Hi,

I'm a native speaker of Swedish, and I've noticed a typo in the Swedish translation.

The word "Spearera" should be "Separera".

Ulf

**Comment by SMed79** [comment]
Hi, 
you can help for translation on crowdin.
https://crowdin.com/translate/decentraleyes/5/enus-sv#100

**Comment by Synzvato** [comment]
@ulf33286 Would you be okay with helping out on Crowdin (as suggested by @SMed79)? I am seeing a lot of open suggestions for the Swedish locale, that you as a native speaker might be able to assess.
