### ISSUE TITLE
Add toolbar widget to display intercepted requests

### ISSUE THREAD

**Issue by pmaziere** [Synzvato/decentraleyes#18]
It would be nice to have an optional icon to put in whatever toolbar that would indicates the number of url intercepted and replaced by local copies. 

And it would be even nicer if clicking or hovering this icon would display the list of intercepted files or url.

thanks

**Comment by Synzvato** [comment]
I absolutely agree with you on the fact that the add-on should give users a better idea of what it's actually up to in the background. Implementing a dynamic toolbar icon, along with some UI panels is a good next step and this will definitely be looked into. I think Firefox for mobile will need a custom interface.

Thanks @pmaziere for bringing this up, and for the suggestions!

**Comment by rmenessec** [comment]
Unless I'm missing a secret Addon Bar, Fennec solutions seem to be one or more of:

- Pop-ups
- Dynamic menu items ([uBlock Origin](https://github.com/gorhill/uBlock/))
- Page overlay ([Ghostery](https://ghostery.com/), optional)

Although, if someone's written an auto-hiding Addon Bar for Fennec that I just can't find... ? 😁

(And, if no one's written one, I'd love to see one. Hint, hint.) 😁

**Comment by TraderStf** [comment]
Browser ~show source / inspector - network or ressources or timeline :)

**Comment by Synzvato** [comment]
The toolbar widget has since been implemented. Be sure to use Decentraleyes ```v2.0.0``` (or higher).
