### ISSUE TITLE
Make showing injection counts on icon optional

### ISSUE THREAD

**Issue by JGH1000** [Synzvato/decentraleyes#185]
Thanks a lot for providing and maintaining this great extension!

A small suggestion - would it be possible to implement an option to hide the counter in the icon? Same as in uBlock etc.
![screenshot from 2017-08-07 15 07 15](https://user-images.githubusercontent.com/27884805/29014127-6c1bfe10-7b82-11e7-8d30-13b252eca21d.png)

It's not that distracting but some people will appreciate a slightly cleaner UI. Many thanks for considering this!

**Comment by jawz101** [comment]
The icon really doesn't do anything for that matter, but I think Google makes you have one in the top bar or something.  In Firefox there isn't even an icon to show.

I'd just right click on it and hide from the menu.  If it actually showed a list of what it's "Decentraleyes'd" on the current open tab it might be interesting.  Otherwise, it's kinda a useless gui.

**Comment by Synzvato** [comment]
> Thanks a lot for providing and maintaining this great extension! A small suggestion - would it be possible to implement an option to hide the counter in the icon?

Hi @JGH1000. Many thanks for your suggestion, and great to hear you appreciate Decentraleyes! I'm happy to say that this feature is planned for a future version of the extension. Expect it to land soon after this extension is ported to WebExtensions (#173). I hope this addresses your concerns.

>  The icon really doesn't do anything [...].  In Firefox there isn't even an icon to show. [...] If it actually showed a list of what it's "Decentraleyes'd" on the current open tab it might be interesting.

Hello @jawz101, and thanks for trying to help out. The Chromium version does feature a fully working ```GUI```, and its counter does show the amount of local injections for active pages. This rewrite is now being ported over to Firefox. The Chromium version serves as the [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) foundation.

**Comment by JGH1000** [comment]
Thanks a lot @Synzvato, grat to hear that you will also support Firefox. Looking forward to the update.

**Comment by Bisaloo** [comment]
I tested this with the WebExtensions beta. It looks great but I think it is somehow counting injections twice in `Counter for locally injected resources`. The counter on a given page is correct though.

**Comment by Synzvato** [comment]
@Bisaloo I'm pretty sure the counter correctly registers resource injections. The [testing utility](https://decentraleyes.org/test/) first attempts to fetch jQuery from Google Hosted Libraries, and then uses the library to see if it's able to get a valid response from said service. Two injections occur, but only one single resource is injected.

Regular websites don't behave this way, so you should not notice any double injections for the same resources when browsing the rest of the web. Thanks for making sure though!

**Comment by Bisaloo** [comment]
No, you're right. I got confused by what you are describing with the testing utility. Injections are indeed counted as expected on regular websites.
