### ISSUE TITLE
Incorrect detail in FAQ

### ISSUE THREAD

**Issue by methuzla** [Synzvato/decentraleyes#186]
https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions
FAQ has incorrect info & needs a correction:
"You can use this testing utility, Firefox's built-in network monitor CTRL+SHIFT+Q "
No, CTRL+SHIFT+Q is 'exit firefox' (Nightly).
(Got caught out trying it :-D)
Dev tools Net Monitor is CTRL+SHIFT+E 
Please amend. (I would but I don't think I can.)

**Comment by TriMoon** [comment]
On Linux Firefox Nightly the quit shortcut is CTRL+Q

**Comment by methuzla** [comment]
@TriMoon _yes exactly_, that's what I was saying: FAQ has wrong info & needs a correction
(&, check the panel: Nightly says 'exit' where it means 'quit')
Thanks, I've clarified the point above.

**Comment by Synzvato** [comment]
Hi @methuzla, and thanks for reporting this! Apart from the hotkey changes in Nightly, the answer failed to acknowledge any of the other supported browsers. I have decided to rewrite the entire segment.

**Comment by methuzla** [comment]
Thank *you *Thomas.
Apologies for being the bringer of extra work; I'm sure it will be a Fine
Manual :-)

Cheers
 Will (=Methuzla)
