### ISSUE TITLE
Network prediction features cause request leakage

### ISSUE THREAD

**Issue by Synzvato** [Synzvato/decentraleyes#188]
First off, many thanks to @Bisaloo for testing ```beta1``` of the ```WebExtension``` under uncommon conditions, and for finding and reporting this issue. It's great to see that the beta is being thoroughly tested!

#### Currently affected users

This issue affects _early adopters_ of the _beta_ for Firefox who have network prediction set to enabled, and are _not_ using content blockers _(e.g. uBlock Origin)_ that automatically disable this feature by default.

#### General problem description

Despite the fact that Decentraleyes properly redirects requests away from large CDNs, some settings cause browsers to attempt to predict your network traffic, and send requests out before noticing that the request is not supposed to occur. This feature can cause unnecessary request leakage.

#### Resolving the issue

You can fix the issue by rebuilding, and reinstalling Decentraleyes from the very latest commit inside of the ```master``` branch (7d21a1ed924517c3041925da2a82d90a078983fc). The upcoming, packaged, release of ```beta1``` will ship with the fix.

**Comment by evaryont** [comment]
Interesting. Is there no other option than to disable network prediction? I don't use it myself, to be honest, but it does speed up browsing when it does guess correctly.

**Comment by Synzvato** [comment]
> Interesting. Is there no other option than to disable network prediction?

@evaryont I'm unaware of any other options. Other kinds of content blockers such as uBlock Origin are taking the exact same measures. I'm quite sure extensions can't alter the prediction algorithms.

> I don't use it myself, to be honest, but it does speed up browsing [...].

You're absolutely right. The feature will soon be made optional. I'm sure there are those who see this extension as a speed booster, instead of a privacy protection tool. By default, Decentraleyes will disable network prediction, but users who don't mind request leakage should soon be able to re-enable it.

**Comment by LimboSlam** [comment]
I thought there was a way to disable this through about:config? Was that option removed?

**Comment by Synzvato** [comment]
@LimboSlam You can indeed manually disable network prediction through ```about:config```, but you would need to set all of the preference values listed inside of the table below by hand.

| Preference Key Name                     | Value       |
|:--------------------------------------- |:----------- |
| network.dns.disablePrefetch             | ```true```  |
| network.http.speculative-parallel-limit | ```0```     |
| network.predictor.enabled               | ```false``` |
| network.prefetch-next                   | ```false``` |

_Source: Bugzilla@Mozilla (bug no. [1312802](https://bugzilla.mozilla.org/show_bug.cgi?id=1312802))._

Handling this from within the extension is more user friendly, and allows us to revert any changes to user preferences when Decentraleyes is uninstalled, or disabled. I hope this answers your question.
