### ISSUE TITLE
Why do I receive notifications after updates?

### ISSUE THREAD

**Issue by FirefoxMYDEVICE** [Synzvato/decentraleyes#191]
Unsure why Decentraleyes contacted me? If purpose was updating? Thanks, Mozilla Firefox!!😊

**Comment by FirefoxMYDEVICE** [comment]
Unsure why Decentraleyes contacted me? If purpose was updating? Thanks, Mozilla Firefox!!😊

**Comment by Synzvato** [comment]
Hi @FirefoxMYDEVICE, and thanks for getting in touch!

It's to inform users about changes that come with certain updates. If you don't want to be notified, please navigate to ```about:config```, and set ```jid1-BoFifL9Vbdl2zQ@jetpack.showReleaseNotes``` to ```false```.
