### ISSUE TITLE
Latest beta 2.0.0b1 breaks napisy24.pl

### ISSUE THREAD

**Issue by skibbipl** [Synzvato/decentraleyes#193]
Hello,
Since few days I'm unable to load napisy24.pl with decentraleyes enabled. Temporarily I've added domain to the whitelist. I'm using latest nightly 57.

**Comment by Synzvato** [comment]
Hi @skibbipl, and thanks for reporting the problem! I'm happy to say that this bug has been resolved, and that the fix will be included in ```v2.0.0beta2```. Please see related issue #192 for more details.

Again, many thanks, and I hope this addresses your concerns!
