### ISSUE TITLE
Is there support for non-minified resources?

### ISSUE THREAD

**Issue by gkrishnaks** [Synzvato/decentraleyes#194]
Hi.
I run Linux Mint 17.2 and Firefox 56. Installed Decentraleyes addon today, was just checking how it delivers content from local.  In crowdcompass.com, jquery.min.js was delivered from local storage by the addon as I could see the comment in debugger. But jquery.js in the same site did not get delivered from local, but a live network call was made to get it. 
Is this working as expected? Is there a way to make Decentraleyes load it from local?
https://imgur.com/a/17JGh 

Thanks.

**Comment by Synzvato** [comment]
Hi @gkrishnaks, and many thanks for sharing your concerns!

> In crowdcompass.com, jquery.min.js was delivered from local storage by the addon [...]. But jquery.js in the same site did not get delivered from local, but a live network call was made to get it.

Even though that second file is called ```jquery.js``` it's actually minified, too. Decentraleyes does have full support for non-minified resources. The reason the request isn't being intercepted, is that the file is hosted by the owner of the website, and not by a large CDN. It is absolutely working as expected here.

> Is there a way to make Decentraleyes load it from local?

There's no proper way for any extension to assess what the contents of the file are supposed to be. Even I still don't know what version of what library we're looking at exactly, cause it hasn't been labeled.

This does not affect the main goal of the project, which is to prevent as many requests to large third party CDNs as possible, to protect online privacy. Guessing what file to inject would inevitably break pages.

Thanks again, and I hope this answers your questions. If not, be sure to let me know!

**Comment by gkrishnaks** [comment]
Hi @Synzvato . Thank you for the detailed answer. I got it! 
I understand the main goal of the project - please continue the great work! :)
