### ISSUE TITLE
AAK-Cont freezes up during initial page load

### ISSUE THREAD

**Issue by themagicteeth** [Synzvato/decentraleyes#195]
Using:
Firefox Nightly 57
Decentraleyes 2.0.0beta1
uBlock Origin with defaults

Issue:
[Anti-Adblock Killer Continued's Gitlab](https://xuhaiyang1234.gitlab.io/AAK-Cont/) continuously loads until Decentraleyes is disabled. Once disabled the page instantly loads. I have not tested this on other Gitlab pages yet.

Below are the only scripts/stylesheets as linked in the source:

    <link rel="stylesheet" href="css/style.css">

    
    <link rel="stylesheet" href="css/animate.min.css">

    
    <link rel="stylesheet" href="css/hover.css">

    
    <script src="//code.jquery.com/jquery.min.js"></script>

**Comment by Synzvato** [comment]
Hi @themagicteeth, and thanks for reporting your problem! I'm happy to say that this issue has been fixed, and that the fix will be included in ```v2.0.0beta2```. Please see #192 for more details.
