### ISSUE TITLE
Support Patreon with block missing enabled

### ISSUE THREAD

**Issue by jhsagl4a** [Synzvato/decentraleyes#199]
In the settings when second checkbox is marked https://www.patreon.com/namewhichyousupport doesn't work.
May be you can add this 2 in your addon
```
https://cdnjs.cloudflare.com/ajax/libs/react/15.6.1/react-dom.min.js
https://cdnjs.cloudflare.com/ajax/libs/react/15.6.1/react-with-addons.min.js
```

**Comment by Synzvato** [comment]
Hi @jhsagl4a, and thanks for sharing your concerns. Please see related issue #78 for more details.
