### ISSUE TITLE
The Add-ons Manager listing is somewhat confusing

### ISSUE THREAD

**Issue by RoxKilly** [Synzvato/decentraleyes#20]
First off, congrats on releasing 1.2.2.  By far my favorite new feature is compatibility with Firefox for Android!!  Thank you :-)

I opened this thread to raise a couple of quick points about things that might confuse users.  If you open the options page `Firefox Add-ons >> Decentraleyes Options`, you will notice two things:

1. A FAQ list which has good questions but no answers!

2. An option to `Add comments to locally fetched file`: the description seems to suggest that a comment at the top of a file will indicate that it was served by the add-on.  However, where can we see this file? The browser's Network logger does not show these files since the request is never made to the remote server. To replicate, open a new tab, Press Ctr+Shift+Q to open the Network logger, and navigate to [the test utility](https://decentraleyes.org/test/).  Notice that the JS files do not show up in the network log.

**Comment by Synzvato** [comment]
Thank you, and my pleasure! I'm very glad you like the new version and the mobile support.

> 1\. A FAQ list which has good questions but no answers!

You're absolutely right. For some reason, hyperlinks are not clickable inside the Add-ons Manager, even though they should be (and are on the [download page](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/)). I have updated the description on the download page to include full links. I don't think that will update the description of this release, though.

> 2\. [...] Add comments to locally fetched file: the description seems to suggest that a comment [...] will indicate that it was served by the add-on. However, where can we see this file?

You can see the injected files inside of the Debugger tab ```CTRL``` + ```SHIFT``` + ```S```. Even though no requests will leave your machine, the code will be injected into the environment and should appear there.

I hope this will allow you to view the comments. If you have any ideas on how to make all this more clear to other end-users, suggestions are always welcome!

**Comment by Synzvato** [comment]
@RoxKilly: I have updated [this FAQ answer](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#where-can-i-see-its-status-or-in-what-way-it-impacts-network-activity) to make it a tad less confusing and more informative. I believe that this properly addresses your second concern.

**Comment by RoxKilly** [comment]
Thanks for the tip about the Debugger. I can see the comment at the top of the injected JavaScript.

**Comment by Synzvato** [comment]
Awesome, glad I could help @RoxKilly, and many thanks for your continued involvement!
