### ISSUE TITLE
Breaks embedded Disqus comment sections

### ISSUE THREAD

**Issue by opav** [Synzvato/decentraleyes#201]
With decentraleyes, site with comments sections that rely on discus.com is badly affected,

The entire discus section at the end of pages are missing.

I can whitelist the main site but obviously this is not the solution when so many sites uses Discus, its impossble to whitelist all of them.

Can decentraleyes whitelist just discus.com?  I tried, doesn't work.

**Comment by Synzvato** [comment]
Hi @opav, and many thanks for sharing your concerns! Could you please let me know what version of the extension you are using. Could you also include a link to a page that suffers from the issue?

**Comment by opav** [comment]
[http://www.breitbart.com/news/trump-issues-stark-threats-to-north-korea-and-iran-at-un/](url)
is just one of many pages on Breitbart.com that won't load the discus section when page is scroll down to bottom.

But now while playing with the options, I found out that if (Block request for missing resource) is uncheck, Breitbart.com discus section will load.  

What is the purpost of this option, seems unchecking it should be the default?

**Comment by opav** [comment]
Sorry the version 1.3.10, to illustrate the issue, the entire area in red rectangle is missing if I check that decentraleyes option.

![Missing section in Red](https://i.imgur.com/yseLeXB.png)

**Comment by Synzvato** [comment]
I'm glad to hear you've managed to resolve the issue. It's an advanced option for users who prefer to manually whitelist any third parties on a per-website basis. The checkbox is disabled by default. The next major release ```v2.0.0``` will display an "Advanced" badge next to the option. I hope this helps!

**Comment by opav** [comment]
Thanks, I see.  I must have checked that option previously, will leave it unchecked to avoid the trouble of whitelisting manually.  Thanks again.
