### ISSUE TITLE
Locally serve Google Font resources

### ISSUE THREAD

**Issue by EC-O-DE** [Synzvato/decentraleyes#209]
http://www.thephphero.com/how-to-host-google-fonts-locally/

https://github.com/jakubpawlowicz/clean-css/issues/632

https://security.stackexchange.com/questions/89932/gstatic-com-resolves-to-local-isp

https://encrypted.google.com/search?&q=gstatic+to+local

**Comment by Synzvato** [comment]
I have marked this as a duplicate of related issue #34.

**Comment by Gitoffthelawn** [comment]
@Synzvato #34 is closed, did you want to reopen that?
