### ISSUE TITLE
Breaks flash loading at minigames.mail.ru

### ISSUE THREAD

**Issue by LaxrMediumWas** [Synzvato/decentraleyes#21]
for example this game: https://minigames.mail.ru/durak

**Comment by Synzvato** [comment]
Thanks for reporting this, it will be looked into! As a temporary fix, you could add ```minigames.mail.ru``` to the whitelist (```CTRL```+```SHIFT```+```A``` > ```Extensions``` > ```Decentraleyes``` > ```Preferences```).

**Comment by Synzvato** [comment]
Caused by the same issue responsible for bug #16.
