### ISSUE TITLE
Will there be any further updates for Pale Moon ?

### ISSUE THREAD

**Issue by graciecat** [Synzvato/decentraleyes#211]
Now that 2.0 is out, is this completely WebExtensions, or is it a hybrid of WebExt and XUL? Is it usable in Pale Moon?

Will there be any further updates to the XUL branch for Pale Moon and similar browsers?
If not, is it safe to continue to use 1.3.10?

**Comment by Synzvato** [comment]
Hi @graciecat, and thanks for sharing your concerns! 

> Now that 2.0 is out, is this completely WebExtensions [...]? Is it usable in Pale Moon?

Version ```2.0.0``` is not a hybrid extension, and cannot be installed on Pale Moon (or similar browsers).

> Will there be any further updates [...] for Pale Moon [...] If not, is it safe to [...] use 1.3.10?

It's definitely safe to continue to use version ```1.3.10```, and the Pale Moon compatible codebase will receive maintenance updates, as well as library bundle additions, for as long as absolutely possible.

I hope this addresses your concerns. If not, feel free to re-open the issue!

**Comment by Synzvato** [comment]
I'm marking this as a duplicate of related issue #190.

**Comment by graciecat** [comment]
Although you closed this, you didn't actually answer the title question, which was, will there be any further updates for Pale Moon?

**Comment by Synzvato** [comment]
> [...] the Pale Moon compatible codebase will receive maintenance updates, as well as library bundle additions, for as long as absolutely possible. I hope this addresses your concerns.

**Comment by Synzvato** [comment]
@graciecat The previously given answer is the best one I can give you at the moment:

> [...] the Pale Moon compatible codebase will receive maintenance updates, as well as library bundle additions, for as long as absolutely possible. I hope this addresses your concerns.

Please post any further replies under related issue #190. Thanks in advance.
