### ISSUE TITLE
Does not work with Subresource Integrity

### ISSUE THREAD

**Issue by Crumbi** [Synzvato/decentraleyes#212]
First thanks for this great Add-On.

Unfortunately it does not work with resources that are secured by integrity checksums.
https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/

The following sample works (and loads jQuery if checksum matches) with Firefox 56.0.1 if Decentraleyes is disabled, but not if it Decentraleyes is enabled.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
<head>
	<title>CDN Resource Link with checksums</title>
	<meta http-equiv="content-type" content="application/xhtml+xml; charset=utf-8" />
	<meta name="robots" content="nindex,nofollow,noodp,noydir,noarchive" />
	<script src="//code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
</head>
<body>
  <p>jQuery Library <span class="js-info">not </span>loaded.</p>
  <script type="text/javascript">
        $(".js-info").hide()
    </script>
</body>
</html>
```

Would be great if this issue could be solved. Thanks,

**Comment by Synzvato** [comment]
Hi @Crumbi, and thanks for sharing your detailed findings!

This is a known issue. It currently affects only a handful of websites, but this will (of course) change as adoption grows. I'm happy to say that said bug is top-priority during this development iteration. It seems that a recently announced ```API``` might help to turn things around. Any updates will be posted in #16.

I hope this addresses your concerns. If not, feel free to let me know!

**Comment by Synzvato** [comment]
@Crumbi I have decided to create a bug ([```1419459```](https://bugzilla.mozilla.org/show_bug.cgi?id=1419459)) on Mozilla's bugtracker. Upvotes are welcome.
