### ISSUE TITLE
Options button broken in private browsing mode

### ISSUE THREAD

**Issue by hfr-hfr** [Synzvato/decentraleyes#214]
When in Firefox's "private mode", toolbar widget is clickable and opens its info window, but:
- "Options" not clickable
- Doesn't show the emulated CDN, although counter indicates action

![x](https://user-images.githubusercontent.com/30601795/31767915-4f294c52-b4cd-11e7-93a6-f2053c8bc170.png)

When in Firefox's "normal mode", the above works as intended.

**Comment by Thorin-Oakenpants** [comment]
confirmed in FF56. Info not shown (domain, library, whitelisting button). Options button is clickable but does not do anything. Counter increases by 2 on each test (if that's meant to be correct, it also does this in normal windows)

normal windows
![dc-normal](https://user-images.githubusercontent.com/16656956/31780546-7f9dbd3e-b552-11e7-9468-11bb909cd9da.png)

private browsing mode
![dc-private](https://user-images.githubusercontent.com/16656956/31780557-86c644e6-b552-11e7-9ba6-b4f4c08e94f7.png)

**Comment by 8wy1ok** [comment]
Browser console error that is thrown: (tested on Nightly)

`TypeError: popup.backgroundPage is undefined [Learn More]           popup.js:351:1`

**Comment by Kasijjuf** [comment]
FWIW, Privacy Badger does a similar thing in Private browsing mode. The list of trackers only shows up on normal mode.

**Comment by Synzvato** [comment]
Hi everyone, and thanks for sharing your detailed findings and concerns!

As pointed out by @Kasijjuf, any website-specific information is intentionally absent from private browsing mode. This might change in the future. Either way, the options button should not be unresponsive.

I'll be dedicating this issue to the underlying bug. Feel free to open a separate issue, if you're interested in discussing the extension's behavior in private mode. Thanks again! I'll be sure to keep you all posted.

**Comment by Synzvato** [comment]
> Counter increases by 2 on each test ([...], it also does this in normal windows)

@Thorin-Oakenpants This is expected behavior. It's because the testing utility requests the very same resource twice. So, two injections occur, but only one unique resource is injected. Good catch though!

**Comment by Synzvato** [comment]
Decentraleyes ```v2.0.1``` has since been published. Installing the update should solve the issue.

**Comment by Synzvato** [comment]
@hfr-hfr @Thorin-Oakenpants I have implemented a [messaging system](https://github.com/Synzvato/decentraleyes/commit/6b5c34efc13e604a50aa2e1c2d7413a484ddc7c5) in order to achieve complete feature parity, so ```v2.0.4``` doesn't lack any features when used within ```Private Browsing``` contexts.

**Comment by Thorin-Oakenpants** [comment]
I saw that :+1:  .. still increases the count by two (not that it matters) - nvm, that's the test, not PB mode specific :headbutt:
