### ISSUE TITLE
Breaks login/register popup on twitch.tv

### ISSUE THREAD

**Issue by SW1FT** [Synzvato/decentraleyes#22]
1. Access http://www.twitch.tv/.
2. Click on Login or Register.
3. Notice the popup that contains the login/register form is completely blank when Decentraleyes is on.

**Comment by RoxKilly** [comment]
Same issue here. Decentraleyes 1.2.2, Firefox 43.0.2, Windows 7 x64.  Problem goes away if I disable Decentraleyes

**Comment by Synzvato** [comment]
@SW1FT Thanks for reporting the issue! It seems to have something to do with the page's security settings in combination with an inline frame that loads additional content. This will be looked into.

@RoxKilly Thanks for following up.

> Also, adding twitch.tv or www.twitch.tv to the whitelist does not help

The content is loaded from within another context. I believe this to be part of the underlying problem. Adding ```passport.twitch.tv``` to your whitelist should keep the login section from breaking.

**Comment by Synzvato** [comment]
Caused by the same issue responsible for bug #16.
