### ISSUE TITLE
Broken by «Privacy Related "about:config" Tweaks»

### ISSUE THREAD

**Issue by stemy2** [Synzvato/decentraleyes#225]
Hello,

I followed the recommendation of https://www.privacytools.io/#about_config and changed some parameters in about:config. And it seems that some of these parameters prevent decentraleyes to work correctly, now it does absolutely nothing. Wich parameter(s) have i to change ?

Thanks.

**Comment by Synzvato** [comment]
Hi @stemy2, and thanks for sharing your concerns. What exact versions of Decentraleyes and Firefox are you using, and what makes you believe it's doing nothing? Please share additional details. Thanks!

**Comment by stemy2** [comment]
The problem is reolved itself.

**Comment by Synzvato** [comment]
Great to hear, and many thanks for letting us know!
