### ISSUE TITLE
Metadata stripping re-activates on add-on reload

### ISSUE THREAD

**Issue by wiredrunner** [Synzvato/decentraleyes#227]
I have everything unchecked (Chrome) but 'Display Injection Counts on Icon' on 2.0 and still get 

"Warning:
This extension failed to modify the request header "Referer" of a network request because the modification conflicted with another extension (uMatrix)."

Sometimes the error shows on the UMatrix extension.   If Decentraleyes hid the referrer on all requests as opposed to just cdn requests I'd just disable the option on UMatrix.  I'm going to try a couple of referrer extensions and see if the error continues.

**Comment by Synzvato** [comment]
Hi @wiredrunner, and thanks for reporting your findings! Could you send me one or more websites that cause the warning to be shown on your end? Additional details would help me reproduce the issue.

**Comment by wiredrunner** [comment]
It seems it was only happening on a single website and as long as decentraleyes is the last extension installed the error doesn't happen at all.

**Comment by EC-O-DE** [comment]
Hmm.

**Comment by Synzvato** [comment]
@wiredrunner I see. Could you please give me the full URL of the page in question?

**Comment by wiredrunner** [comment]
http://www.breitbart.com

**Comment by Synzvato** [comment]
@wiredrunner Thanks! I'm going to run some tests to see if I can reproduce your problem, and will share the results. By the way, since I have the information, feel free to delete the comment (if preferred).

**Comment by wiredrunner** [comment]
Just happened on http://www.fiercewireless.com

**Comment by Synzvato** [comment]
Thanks to your detailed instructions, I have been able to reproduce your problem on my side. The issue occurs after extension reloads, and browser restarts. Expect the fix to land in the very next release.

**Comment by wiredrunner** [comment]
That's great thank you.

**Comment by Synzvato** [comment]
Decentraleyes ```v2.0.1``` has since been published. Installing the update should solve the issue.
