### ISSUE TITLE
Is Decentraleyes compatible with Opera?

### ISSUE THREAD

**Issue by PinkLouie** [Synzvato/decentraleyes#233]
Can you launch the extension on opera.addons.com? Opera add-ons store is better curated, and it's necessary for Opera users. Installing chrome extensions on Opera can, sometimes, be a bit more complicated.

Thanks anyway, your extension is great.

**Comment by Synzvato** [comment]
Hi @PinkLouie, and thanks for getting in touch! I am very happy to hear you like the extension.

You can find any Opera-compatible releases [here](https://addons.opera.com/extensions/details/decentraleyes). In case you're inquiring about the ```v2.0.0``` update: It has been submitted, and is currently awaiting moderation. Does this answer your question?
