### ISSUE TITLE
Where do you stand with regards to Cloudflare?

### ISSUE THREAD

**Issue by YouMustKnowPrivacyIsOurRight** [Synzvato/decentraleyes#236]
https://github.com/privacytoolsIO/privacytools.io/issues/364

Well, what do you think?

**Comment by anarcat** [comment]
that link is a 404

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
It's nuked for whatever reason. Duh.

here:
https://github.com/mozilla-mobile/focus-android/issues/1743

**Comment by Synzvato** [comment]
Hi @YouMustKnowPrivacyIsOurRight, and thanks for getting in touch! The fact that a handful of big corporations (e.g. ```Cloudflare Inc.```, ```StackPath LLC```, ```Amazon.com, Inc.```, etc.) now serve large portions of the internet, without all this being sufficiently apparent to regular surfers, is very concerning indeed.

Decentraleyes takes care of quite a few popular libraries on ```CDNJS``` (a Cloudflare-sponsored CDN), but the same strategy cannot be applied to ```MITM```-proxies. I'm personally thinking of compiling a list of known giants, and introducing a decentralization score indicator. That would at least raise public awareness.

To clarify, I'm not just talking about ```MITM```-proxies, but I feel this also applies to large hosting providers.

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
> compiling a list of known giants, and introducing a decentralization score indicator

...and show some alternatives for example. privacytools.io, prism-break.org, and so on.

You add-on might be included in TBB. https://trac.torproject.org/projects/tor/ticket/22089
