### ISSUE TITLE
Breaks the official Microsoft homepage

### ISSUE THREAD

**Issue by Noexpert** [Synzvato/decentraleyes#237]
Hi,

issue as above.
Disabling the extension loads the site, otherwise a blank page is displayed,

**Comment by Synzvato** [comment]
Hi @Noexpert, and thanks for the report. I'm personally unable to reproduce the problem. Could you let me know which localized version of ```www.microsoft.com``` you are attempting to visit? Thanks!

**Comment by Noexpert** [comment]
Hi there.

Turns out it was one of the filters on uBlock.
My apologies.

**Comment by Synzvato** [comment]
No worries, @Noexpert, and many thanks for coming back here to explain what happened!

**Comment by Noexpert** [comment]
Hi,

I'm taking the liberty to re open this issue.
Please visit this (or indeed any Microsoft answers page):
https://answers.microsoft.com/en-us/windows/forum/windows_10-networking/problem-importing-bookmarks-from-firefox-into-win/1bcb9d0a-eff0-4453-8ff3-a74260db76b4?auth=1

and then try to expand the Replies panel at the bottom of the page.
With Decentaleyes enabled, it cannot be expanded to reveal more replies.

Disabling the add-on, refreshing the page, it then works.
This is on Firefox 57.

Thanks

**Comment by Synzvato** [comment]
Hi again @Noexpert, and thanks for sharing your concerns. I'm unable to reproduce the issue, as I was able to expand the panel with Decentraleyes enabled. Also, no injections occur on the answers site.
