### ISSUE TITLE
Breaks https://stefansundin.github.io/2fa-qr/

### ISSUE THREAD

**Issue by haarp** [Synzvato/decentraleyes#24]
On https://stefansundin.github.io/2fa-qr/, it produces the following error:

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://code.jquery.com/jquery-2.1.4.min.js. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

and breaks the site.

**Comment by RoxKilly** [comment]
@Synzvato  when you tag an issue with `duplicate`, it may be a good idea to add a reference to the initial bug (if you have it).

**Comment by Synzvato** [comment]
@haarp Thanks for reporting the issue!

It's caused by the same problem that is causing some other websites to break (see #16, #17, #22) and will be looked into. For now, adding ```stefansundin.github.io``` to the whitelist should help.

@RoxKilly You were mighty quick, I had yet to comment on the issue.
