### ISSUE TITLE
Update rulesets independently from the extension

### ISSUE THREAD

**Issue by Rictusempra** [Synzvato/decentraleyes#243]
So that you don't have to draft a release for updating the rule sets, just like uBO

**Comment by elypter** [comment]
the best would be a collaboration with ublock or nano blocker on the core level, or at least a compatible syntax

**Comment by Synzvato** [comment]
Hi @Rictusempra, and thanks for sharing your thoughts! Since this extension's rulesets are based on market share statistics by W3Techs, there is no need for frequent updates. Web presence of CDNs and libraries does not typically change over night. Please see #91 for a related brainstorming session.
