### ISSUE TITLE
Decentraleyes breaks Mini Quad Test Bench

### ISSUE THREAD

**Issue by atomGit** [Synzvato/decentraleyes#244]
waterfox 56.0.1
decentraleyes 2.0.1

decentraleyes breaks the charts on this page:
`https://www.miniquadtestbench.com/motor-explorer.html`

i think it might be one of these scripts causing the problem, but i'm not sure...
`https://code.jquery.com/jquery-1.12.4.min.js`
`https://code.jquery.com/jquery-2.1.4.min.js`

**Comment by dualscyther** [comment]
This one too:
https://10fastfingers.com/typing-test/english

No text appears until I disable Decentraleyes. I'm also running Privacy Badger, UBlock Origin and HTTPS Everywhere. I'm on Firefox 57.0.3

**Comment by Synzvato** [comment]
Hi @atomGit and @dualscyther, and thanks for reporting the issue!

It's a known problem, so please see issue #16 for more information. In the meantime, please whitelist the domains in question. I will make sure that the next release will ignore resources on these websites.
