### ISSUE TITLE
Does this differ from Web Boost and Local Load?

### ISSUE THREAD

**Issue by ravenise** [Synzvato/decentraleyes#245]
And which is a better option? Is there not code from the open source Web boost that could be used to enhance decentraleyes? The two extensions conflict with one another.

https://chrome.google.com/webstore/detail/web-boost-wait-less-brows/ahbkhnpmoamidjgbneafjipbmdfpefad

**Comment by elypter** [comment]
there was also a now discontinued addon called local load

**Comment by Synzvato** [comment]
Hello @ravenise and @elypter, and many thanks for getting in touch.

> What is the difference between decentraleyes and Web Boost? And which is a better option?

While Decentraleyes aims to improve both page speed and privacy, Web Boost has no goals outside of performance. It does not strip sensitive data from unpreventable CDN-requests and does not disable link prefetching (which can lead to CDN-request leakage). In addition, it is only available in (US) English.

> there was also a now discontinued addon called local load

Local Load was different in the sense that it looked for specific ```data-replacement``` attributes on a given page. So, once installed, it did allow you to load local resources, but only for pages that you (or someone else) prepared specifically. It did not prevent arbitrary sites from connecting you to delivery networks.
