### ISSUE TITLE
Enable target language Czech on Crowdin

### ISSUE THREAD

**Issue by MikkCZ** [Synzvato/decentraleyes#246]
Hi @Synzvato . Can you please enable Czech (cs) localization on CrowdIn? I would like to promote it through our local community @MozillaCZ.

**Comment by Synzvato** [comment]
@MikkCZ I have added [Czech](https://crowdin.com/project/decentraleyes/cs) to the project. Thanks in advance for the support. Much appreciated!

**Comment by MikkCZ** [comment]
Thank you. I will prepare some tweets and Facebook posts for this week. I think we should be 100% before the next weekend.

**Comment by MikkCZ** [comment]
@Synzvato the Czech translation is ready in Crowdin. How can I get all the strings approved?

**Comment by Synzvato** [comment]
Many thanks for everything, @MikkCZ! I have raised one minor issue, but all of your other translations have just been approved. If all goes well, Czech should land in the very next release (```v2.0.3```).
