### ISSUE TITLE
Decentraleyes breaks OpenWeatherMap

### ISSUE THREAD

**Issue by TerkiKerel** [Synzvato/decentraleyes#247]
Hi,

Please check this link:
https://openweathermap.org/city/745044

At console it gives below error and thats why the page fails to load:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://code.jquery.com/jquery-1.9.1.min.js. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

But decentraleyes extension does not blocks request if they are not exist locally. 

When I disable decentraleyes extension and refresh the page, the page loads properly.

I have not change any settings of extension.

Thank you

**Comment by Synzvato** [comment]
This is a known issue (see #16). The website's security settings keep Decentraleyes from injecting any libraries into that page. For now, adding ```openweathermap.org``` to your domain whitelist should solve your problem. A permanent solution is currently [being discussed](https://github.com/Synzvato/decentraleyes/issues/16#issuecomment-348766926). Please do let me know if this helps!
