### ISSUE TITLE
Does this tool support other Google API domains?

### ISSUE THREAD

**Issue by grumpygeek** [Synzvato/decentraleyes#248]
Is apis.google.com covered, or will it be?  I'm reluctant to enable js for it uMatrix not knowing if DCE will catch it.  I have DCE set to block missing resources which is how I want it, but not clear if that means it will block js requests for all sites it does not include.

**Comment by Synzvato** [comment]
Decentraleyes supports ```googleapis.com```, but not ```apis.google.com```.  Do you happen to have an example of a site that depends on that specific domain? If so, could you please post it here or send it by email?

**Comment by dryoma** [comment]
I'd second the request.

As an example, https://readms.net/ I have definitely met other sites, but can't remember them right away. Will link to them here if needed.

**Comment by ArchangeGabriel** [comment]
@Synzvato https://www.flightradar24.com/

**Comment by ArchangeGabriel** [comment]
But there is nothing Decentraleyes can do about the ones loaded there.

**Comment by Synzvato** [comment]
Conclusively: Decentraleyes does not intercept requests for ```apis.google.com``` and you were right to keep it blocked. Also, @ArchangeGabriel is right as responses are unversioned and expire upon arrival.

I hope this properly answers your initial question. If not, feel free to re-open this issue.
