### ISSUE TITLE
The explanation of the approach is incorrect

### ISSUE THREAD

**Issue by rob-stewart** [Synzvato/decentraleyes#249]
The description never actually says that Decentraleyes retrieves content from CDNs or that it uses scrubbed headers to make its requests safer. As described, I thought Decentraleyes had its own, local collection of content that it served. Thus, I suggest changing, "The aim of this add-on is to cut-out the middleman by providing lightning speed delivery of local (bundled) files to improve online privacy," to something more like the following:

_This add-on smartly caches content from those third parties without information that identifies you. That reduces your data usage and virtually eliminates their ability to track you._

**Comment by TriMoon** [comment]
This extension **actually does** serve it's **own local content** versions, it does **not** download and cache "yet"...

**Comment by Synzvato** [comment]
Hi @rob-stewart, and thank you for sharing your concerns. As correctly stated by @TriMoon, it does in fact come with locally injectable content. It's also worth noting that request sanitation only comes into play when a requested resource is not locally available. It's optional, and does not increment the counter.
