### ISSUE TITLE
Add list of CDN domain names to the wiki

### ISSUE THREAD

**Issue by glacambre** [Synzvato/decentraleyes#25]
Hi,
I'm using both uMatrix and decentraleyes. I would like to add a few rules to uMatrix to allow requests to the CDN that decentraleyes mirrors.
This is the list of domains that I managed to build based on the description of the plugin that I found on AMO (https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/) :
```
upcdn.b0.upaiyun.com
lib.sinaapp.com
libs.baidu.com
yastatic.net
cdn.jsdelivr.net
ajax.microsoft.com
ajax.aspnetcdn.com
code.jquery.com
cdnjs.cloudflare.com
ajax.googleapis.com
```
Is this list correct? Are there domains in that list that decentraleyes doesn't take care of? Does decentraleyes take care of more CDN?
It would be nice to have an exhaustive list of domain names on the wiki.

**Comment by adisib** [comment]
The domains as present in the source code file /lib/mappings.js is as follows:
```
ajax.googleapis.com
ajax.aspnetcdn.com
ajax.microsoft.com
cdnjs.cloudflare.com
code.jquery.com
cdn.jsdelivr.net
yandex.st
libs.baidu.com
lib.sinaapp.com
upcdn.b0.upaiyun.com
```
This seems to match the list you got from AMO.

**Comment by Synzvato** [comment]
@glacambre Thanks for sharing your thoughts on this. As @adisib pointed out, you guessed pretty much right. The domain ```yastatic.net``` is not yet supported (but will be soon). Yandex CDN content was previously served from a different domain (```yandex.st```) which is now deprecated, but still widely used.

As per your request, I have added the list of domains to the Wiki's [FAQ page](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#why-doesnt-it-deliver-resources-from-cdns-i-block-using-a-different-add-on).

**Comment by glacambre** [comment]
That was pretty fast!
Thanks,
