### ISSUE TITLE
Decentraleyes breaks Datawrapper's blog

### ISSUE THREAD

**Issue by kannes** [Synzvato/decentraleyes#252]
https://blog.datawrapper.de/colorblind-check/ fails to load an embedded map due to 'None of the “sha384” hashes in the integrity attribute match the content of the subresource.'

If I disable decentraleyes it loads fine.

I think this is the problematic bit:
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js" integrity="sha384-8gBf6Y4YYq7Jx97PIqmTwLPin4hxIzQw5aDmUg/DDhul9fFpbbLcLh3nTIIDJKhx" crossorigin="anonymous"></script>`

**Comment by Synzvato** [comment]
Hi @kannes, and many thanks for this detailed report of your findings.

This is a known issue (see #16). The website's security settings keep Decentraleyes from injecting any libraries into that page. For now, adding ```blog.datawrapper.de``` to your domain whitelist should solve your problem. A permanent solution is currently [being discussed](https://github.com/Synzvato/decentraleyes/issues/16#issuecomment-348766926). Please do let me know if this helps!
