### ISSUE TITLE
Injection badge re-appears on add-on reload

### ISSUE THREAD

**Issue by 10bass** [Synzvato/decentraleyes#253]
This very well may be a strange Vivaldi issue (webextension settings load issue that uBlock/ScriptSafe/Tampermonkey don't run into) so of course feel free to close, but it's worth asking about.

Browser: Vivaldi 1.14.1077.50 (current stable, Chromium 64.0.3282.170 base)
Issue: Injection count is still displayed when "Display injection counts on icon" is unchecked in options.
Expected behavior: no icon
Current behavior: counter is displayed unless I go into the options, and check then un-check the option. Behaves as expected until the browser is re-launched. Occurs on multiple PCs, with multiple (past) stable versions of Vivaldi.

**Comment by Synzvato** [comment]
Hello @10bass, and many thanks for reporting this! While Firefox seems to be unaffected, I was able to reproduce your issue on various Chromium-based browsers. This should definitely be looked into.

**Comment by Synzvato** [comment]
@10bass Could you please try replicating the bug on ```v2.0.3``` of Decentraleyes? It should be resolved.

**Comment by 10bass** [comment]
v2.0.3 is working for me. Thank you for the quick resolution!
