### ISSUE TITLE
Add Brightcove Player to the default bundle

### ISSUE THREAD

**Issue by nitrocode** [Synzvato/decentraleyes#254]
It would be nice if video.js was used locally instead of the cdn so if we block remote fonts, the icons in html5 videos will still render correctly instead of showing up as square boxes.

Related issue: https://github.com/NanoAdblocker/NanoCore/issues/127

**Comment by Synzvato** [comment]
Hi @nitrocode, and many thanks for sharing your suggestion.

> It would be nice if video.js was used locally instead of the cdn so if we block remote fonts, the icons in html5 videos will still render correctly instead of showing up as square boxes.

The icons are embedded within ```index.min.js```. Said script contains core logic, and is unversioned. This means that it could change at any time, without prior notice. So, I'm afraid it cannot be bundled.

**Comment by nitrocode** [comment]
Hmmm. Who does `index.min.js` belong to? Perhaps I can write up a ticket to request versioning of that file and then could it be added into this project so we can see the buttons?
