### ISSUE TITLE
Decentraleyes breaks the NHM website

### ISSUE THREAD

**Issue by Bisaloo** [Synzvato/decentraleyes#257]
Test url: http://www.nhm.ac.uk/discover/wildlife-photographer-of-the-year-cats-on-camera.html

Tested on a fresh profile with only decentraleyes.

Is this #16?

**Comment by Kasijjuf** [comment]
The images in the article are displaying for me.

I'm running Firefox 56 on Xubuntu 17.10. (firefox package version is 56.0+build6-0ubuntu1)

Filtering/Blocking add-ons I'm using include:
[Decentraleyes 2.0.3](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/versions/2.0.3)
[GNU LibreJS 6.0.13](https://addons.mozilla.org/en-US/firefox/addon/librejs/versions/6.0.13)
[HTTPS Everywhere 2018.2.26](https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/versions/2018.2.26)
[Privacy Badger 2018.2.5](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/versions/2018.2.5)

**Comment by Bisaloo** [comment]
Ah, that's strange. I'm using Nightly and can reliably reproduce.

Console output:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://code.jquery.com/jquery-1.11.2.min.js. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
> None of the “sha256” hashes in the integrity attribute match the content of the subresource.

**Comment by Synzvato** [comment]
Hi @Bisaloo, and many thanks for reporting this. Also, thank you @Kasijjuf for attempting to reproduce the issue on your end. I can confirm that there is a problem with the site (indeed caused by #16).
