### ISSUE TITLE
Decentraleyes breaks the FMA website

### ISSUE THREAD

**Issue by Peter61CM** [Synzvato/decentraleyes#261]
Site: http://freemusicarchive.org/music/charts/all/?genre=all&chart=interest

On the Free Music Archive site selecting something like Most Favourited instead of Most Interesting for example does nothing unless you dissable Decentraleyes for the site. It may be something to do with the Google Hosted Libraries.

**Comment by crssi** [comment]
I have latest FF and latest decetraleyes and I can sort the list by any option.
Maybe some other extension is intrefering.
Did you tried to disable all extensions except Decentraleyes on your test?

**Comment by Peter61CM** [comment]
I have FireFox 59.0.2 64 bit and Decentraleyes 2.0.3. I have dissabled all extensions except Decentraleyes. With Decentraleyes enabled for FMA the sort does not work. With Decentraleyes disabled for FMA the sort works.

**Comment by Cerberus-tm** [comment]
Have you tried it in a new profile?

**Comment by Peter61CM** [comment]
I just tested it on a temporary profile and it works perfectly. Any ideas on how to debug this issue on my working profile as it will be a big job to move to a new profile for such a small problem?

**Comment by crssi** [comment]
Sure... Do you have user.js file? See here: [https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting)

If not then go through pref.js file.

Cheers

**Comment by Peter61CM** [comment]
I don't have a user.js file so I went through the prefs.js file. The ghacks troubleshooting script and guided did not help me. I have also tried clearing the cache.

This is the situation so far:

1. If I create a new profile and install Decentraleyes everything works fine.

2. If I make a copy of my profile and use it FMA is broken. It is broken when I dissable all plugins except Decentraleyes. It is broken when I uninstall all plugins except Decentraleyes.

3. If I delete the prefs.js file so that a new one is created FMA is broken.

Any ideas on how to proceed now?

**Comment by Synzvato** [comment]
@Peter61CM This surely narrows down the possibilities. Could you please navigate to the Decentraleyes ```options``` page, and make sure the _"Block requests for missing resources"_-feature is disabled?

**Comment by Peter61CM** [comment]
@Synzvato The "Block requests for missing resources"-feature was enabled. I disabled it and now the FMA page works correctly with Decentraleyes enabled.

**Comment by Synzvato** [comment]
@Peter61CM That's very nice to hear! The feature prevents requests, even when a resource isn't locally available. It's disabled by default, as it requires you to manually whitelist sites that break as a result.

**Comment by Peter61CM** [comment]
@Synzvato I'm going to keep block requests for missing resources enabled and just whitelist broken sites.

I have one other site in my whitelist. https://starfrosch.com/ Site formatting is broken if you go to the charts.

**Comment by Synzvato** [comment]
> I'm going to keep block requests for missing resources enabled and just whitelist broken sites.

Sounds good! It's definitely the best choice if you don't mind some occasional tinkering.

**Comment by ArchangeGabriel** [comment]
Does Decentraleys tells when they are blocked ressources?
