### ISSUE TITLE
Add additional libraries to the default bundle

### ISSUE THREAD

**Issue by kysoft** [Synzvato/decentraleyes#264]
Please consider adding these libraries :

'bootstrap-select'
'font awesome'

like:
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css

**Comment by Synzvato** [comment]
Hi @kysoft, and thanks for sharing your thoughts!

I don't have any statistics on bootstrap-select that indicate it's popular enough to be a valid candidate, but am happy to say that Font Awesome is on the roadmap. For additional details, please see #37.

**Comment by Synzvato** [comment]
For administrative purposes, I'm marking this issue as a duplicate of related issue #37.
