### ISSUE TITLE
Breaks the YggTorrent website

### ISSUE THREAD

**Issue by Aliaspub** [Synzvato/decentraleyes#268]
problems happen with Decentraleyes activated when you try to connect to your user account of this website (login) and with the left lateral bar which can't be hidden.

**Comment by ArchangeGabriel** [comment]
I just went to the website to check that, and indeed clicking on “S’identifier” (top right) or “Sections” (leftmost) does nothing while both work upon deactivating Decentraleyes for this particular website. Not sure why.

**Comment by crssi** [comment]
Under Decentraleyes settings uncheck "Block requests for missing resources" and you will be fine.

Cheers

**Comment by Aliaspub** [comment]
@crssi indeed, unticking this setting works fine, thank you for your investigation!

**Comment by Synzvato** [comment]
Thanks everyone! Quite a few problems seem to stem from accidentally applied blocking rules. A warning message and a revert-button should drastically reduce these issues. So, expect some improvements.
