### ISSUE TITLE
Add jQuery 1.12.0 to the resource bundle

### ISSUE THREAD

**Issue by bb10** [Synzvato/decentraleyes#27]
It's quite new, but it's already being used on some websites.

**Comment by Synzvato** [comment]
Thanks for sharing your thoughts and findings!

According to [W3Techs' numbers](http://w3techs.com/technologies/details/js-jquery/1.12.0/all) (the project's main source of statistics), at the time of writing, version 1.12.0 of jQuery is used by less than 0.1% of all websites. If it gains traction, it will be included.
