### ISSUE TITLE
Decentraleyes breaks inSCREEN content

### ISSUE THREAD

**Issue by Aliaspub** [Synzvato/decentraleyes#271]
When Decentraleyes is activated on inscreen.tv websites, videos don't start.
For instance for "Canal Fi" accessible on below websites: 
https://canalfi.inscreen.tv/
https://melenchon.fr/
https://lafranceinsoumise.fr/

**Comment by Synzvato** [comment]
Hi @Aliaspub, and thanks for sharing your concerns! I have not been able to reproduce the issue, so I'm curious as to what browser you used, on what platform. Could you let me know here, or via email?

**Comment by Aliaspub** [comment]
Here is what happens on my side (blackened video players):
https://zupimages.net/up/18/17/s7v7.png
https://zupimages.net/up/18/17/rd50.png
Finally, not sure that my issue is due to Decentraleyes. Indeed, after many tests, when I click on "VOIR / AFFICHER EN PLEIN ECRAN" buttons on these webpages, video first image backgrounds are displayed, but videos never start, even Decentraeyes is activated or not.

So perhaps don't close this issue report for the moment, cause it needs more investigation to exclude definitively Decentraleyes from making this issue...
Thank you

**Comment by Synzvato** [comment]
@Aliaspub Thank you for getting back to me on this. Given that the problem persisted even after you disabled Decentraleyes, I'm quite convinced that it's fully unrelated. I'll mark this issue as invalid for now, but feel free to run more personal experiments. A list of steps to reproduce would be very helpful.
