### ISSUE TITLE
Decentraleyes breaks Mes Lieux Paris

### ISSUE THREAD

**Issue by hydrargyrum** [Synzvato/decentraleyes#275]
I'm visiting the site https://meslieux.paris.fr/ and it fails to display properly when decentraleyes is installed. A blank page with an empty button in a corner is shown. On the console, 2 js errors can be found.

When decentraleyes is disabled, the site displays fine.

**Comment by Synzvato** [comment]
Hi @hydrargyrum, and thanks for taking the time to report your findings.

This is a known issue (see #16). The website's security settings keep Decentraleyes from injecting any libraries into the web page. For now, adding ```meslieux.paris.fr``` to the domain whitelist should solve the problem. A permanent solution is currently [being discussed](https://github.com/Synzvato/decentraleyes/issues/16#issuecomment-348766926). Please do let me know if this helps!

**Comment by hydrargyrum** [comment]
Adding the exception fixed the issue, thanks. Looking forward to having a real fix.
