### ISSUE TITLE
Decentraleyes breaks Gazeta do Povo

### ISSUE THREAD

**Issue by anewuser** [Synzvato/decentraleyes#276]
Can you add this domain to the built-in temporary whitelist until #16 is fixed? It is a major newspaper.

`gazetadopovo.com.br`

**Comment by Synzvato** [comment]
Hi @anewuser, and thanks for reporting this.

> Can you add this domain to the built-in temporary whitelist [...]? It is a major newspaper.

Sure. Expect this temporary fix to be present in the upcoming ```v2.0.4```-release.
