### ISSUE TITLE
ajax.googleapis.com angularjs 1.6.5 not cached?

### ISSUE THREAD

**Issue by yuv** [Synzvato/decentraleyes#279]
Thanks for this great extension.  I use it in conjunction with uMatrix and the Logger of uMatrix enables me to make the following observations.

Website: freebusy.io

With Decentraleyes enabled jquery 1.12.4 from ajax.googleapis.com is substituted but the site remains blank.

When I disable Decentraleyes, there is an additional request to ajax.googleapis.com for angularjs 1.6.5.

Any idea why angularjs 1.6.5 is not substituted by Decentraleyes?

Are there instructions somewhere how to contribute the substitution of an additional library?

Thanks again for helping keeping Google's fingers out of our pies!

**Comment by criztovyl** [comment]
By default Decentraleyes should allow the additional request for Angular if it's not available locally. (Unless you enabled to block those.) 

What you might be experience is a bug in the current version of Decentraleyes where due to some CORS limitations.
Could you check your web console (CTRL+ALT+K) for cross-origin errors when you load the page with Decentraleyes enabled?

**Comment by yuv** [comment]
Thanks for the quick reply.  I checked the web console (CTRL+SHIFT+K on Ubuntu 16.04LTS) with Decentraleyes enabled (and my usual uBlock Origin and uMatrix filters).  The relevant output that I see says : 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
<script> source URI is not allowed in this document: “https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js”.
freebusy.io:500
Error: Bootstrap's JavaScript requires jQuery
bootstrap.min.js:6:37
ReferenceError: jQuery is not defined[Learn More]
webapp.min.js:1:15
ReferenceError: $ is not defined[Learn More]
freebusy.io:516:5

and Decentraleyes lists Google hosted jQuery as substituted.

If I disable Decentraleyes temporarily, none of the above console messages appear.  The rest is very similar (a lot of verbosity that I think is irrelevant to the issue).

**Comment by criztovyl** [comment]
So it's the CORS bug.
For now the only work-around AFAIKT is to whitelist the website.

**Comment by yuv** [comment]
OK, thanks. What is the ticket for the CORS bug, to close this one as a duplicate thereof?

**Comment by criztovyl** [comment]
Not sure, maybe #64

**Comment by yuv** [comment]
never mind. find it. Bug #16
