### ISSUE TITLE
Similar add-on: Local Load

### ISSUE THREAD

**Issue by flysch** [Synzvato/decentraleyes#28]
There is a similar add-on called "local load" for firefox available, I am not sure if you are aware of it.

http://www.getlocalload.com/
https://addons.mozilla.org/en-US/firefox/addon/local-load/
it seems to be GPL2 and the last update was in February 2013

There are some old issues that are still not fixed
https://addons.mozilla.org/en-US/firefox/addon/local-load/reviews/

There is also an additional userscript available:
http://userscripts-mirror.org/scripts/show/87361

Maybe it could help you, e.g. to solve bug #16

**Comment by Synzvato** [comment]
Thanks for sharing your thoughts and findings!

Local Load is different in the sense that it looks for specific "data-replacement" attributes in on a given page. When installed, it does allow you to load local resources, but only for pages that you (or someone else) prepared manually. It does not prevent arbitrary websites from referring you to CDNs.

For the same reason, Local Load's source code does not contain answers to the problems this add-on has with some websites that use incompatible, experimental, tags. Nonetheless, I very much like the fact that you decided to make sure if I was aware of Local Load (Extended). Appreciated!

**Comment by Synzvato** [comment]
@flysch I've since decided to create a bug ([```1419459```](https://bugzilla.mozilla.org/show_bug.cgi?id=1419459)) on Mozilla's bugtracker. Upvotes are welcome.
