### ISSUE TITLE
Decentraleyes breaks the Transcend website

### ISSUE THREAD

**Issue by crssi** [Synzvato/decentraleyes#281]
Open [https://www.transcend-info.com/supports/special.aspx?no=3](https://www.transcend-info.com/supports/special.aspx?no=3)
Try to download...
Disable Decentraleyes and try to download.

Cheers

**Comment by Synzvato** [comment]
Hi @crssi, and many thanks for taking the time to report your problem.

This is a known issue (see #16). The website's security settings keep Decentraleyes from injecting any libraries into the web page. For now, adding ```transcend-info.com``` to the domain whitelist should solve the problem. A permanent solution is currently [being discussed](https://github.com/Synzvato/decentraleyes/issues/16#issuecomment-348766926). Please do let me know if this helps!

**Comment by crssi** [comment]
Sorry for reporting duplicate problem and thank you for your great addon.
It is not a problem at all, no need to whitelist. I have just stumbled on this website, and report here to make help you pinpoint possible problem to resolve.
I am glad you are already aware and in search for a solution.
Cheers
