### ISSUE TITLE
Decentraleyes breaks the ManualsLib website

### ISSUE THREAD

**Issue by voxadam** [Synzvato/decentraleyes#282]
When Decentraleyes is active and the site is not whitelisted it is not possible to download content from manualslib.com.

To reproduce:
1.  Browse to https://www.manualslib.com/download/823509/Motorola-Bsr-64000.html
2.  Complete the CAPTCHA challenge
3.  Click the "Get Manual" button

Fedora 28
Linux kernel 4.16.9 SMP x86_64
Firefox 60.0 (64-bit) from Fedora 28 repository
Decentraleyes 2.0.3 from addons.mozilla.org

**Comment by Synzvato** [comment]
Hi @voxadam, and thank you for reporting your problem. Expect the next release (```v2.0.4```) to contain a temporary fix, and know that a permanent solution is in the works. Please see #16 for more details.
