### ISSUE TITLE
Update HTTPS Everywhere configuration guide

### ISSUE THREAD

**Issue by puff-m-d** [Synzvato/decentraleyes#287]
Hello,

Does FAQ "Why am I receiving HTTPS Everywhere-related warnings on Chrome or Chromium?" ( located at https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions ) need to be updated? The "short guide" ( located at https://decentraleyes.org/configure-https-everywhere/ ) does not seem to include the new CDN domains...

**Comment by Synzvato** [comment]
Hi @puff-m-d, and thank you for reporting this! One of the newly supported domains (```sdn.geekzu.org```) is indeed [present](https://www.eff.org/https-everywhere/atlas/domains/geekzu.org.html) inside of the HTTPS Everywhere atlas. I have updated the [configuration guide](https://decentraleyes.org/configure-https-everywhere/).

**Comment by puff-m-d** [comment]
Hello @Synzvato,

Thanks both for your prompt reply and all of your work on this extension. It is very much appreciated!

**Comment by EC-O-DE** [comment]
Smart HTTPS - way better as it doesn't use EFF updated static lists. Also uses less RAM & CPU.
