### ISSUE TITLE
Please add official SeaMonkey support

### ISSUE THREAD

**Issue by JohnDDuncanIII** [Synzvato/decentraleyes#29]
i modified the install.rdf and simply added the needed:
```
 <!-- SeaMonkey -->
    <em:targetApplication>
      <Description>
        <em:id>{92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}</em:id>
        <em:minVersion>2.0</em:minVersion>
        <em:maxVersion>2.39</em:maxVersion>
      </Description>
    </em:targetApplication>
```
and it works perfectly with 2.39 release.
![screen shot 2016-02-01 at 10 49 01 am](https://cloud.githubusercontent.com/assets/9257785/12722191/c4d4a2a6-c8d1-11e5-874a-318efd9e8eb0.png)

**Comment by Synzvato** [comment]
Thanks for bringing this to my attention! It does indeed work on recent versions of SeaMoney, so I'll be sure to add SeaMonkey to the list of supported applications.

**Comment by JohnDDuncanIII** [comment]
Thanks for adding support (officially!). This happens when I try to install it from amo currently. You may need to specify the maxversion or something, like I did in my previous post. It installed fine when I modified the install.rdf with that.

![screen shot 2016-02-13 at 6 30 15 pm](https://cloud.githubusercontent.com/assets/9257785/13030660/17bd6e82-d280-11e5-80ba-cb6eab787d50.png)

**Comment by Synzvato** [comment]
@JohnDDuncanIII My pleasure! That's true. The current release build does not yet have SeaMonkey support, but it will be introduced in the very next update (along with many other changes).
