### ISSUE TITLE
Breaks on mono-project.com

### ISSUE THREAD

**Issue by dw** [Synzvato/decentraleyes#31]
See http://www.mono-project.com/download/ with/without.

Sorry for the terse report. What's the preferred format? I didn't do any digging, but assuming it's a missing lib, do you happily accept PRs for missing libraries?

**Comment by Synzvato** [comment]
Thanks for sharing your concerns!

It should work just fine, unless you enable "block requests for missing resources". If you would like to keep that enabled, just add ```mono-project.com``` to the whitelist (also in preferences).

The websites needs a few relatively rare libraries that are not included. By default, Decentraleyes allows requests for missing resources to keep these kinds of pages from breaking. I am open to suggestions and Pull Requests, but do base any final decisions on various web crawling statistics (#7).
