### ISSUE TITLE
Errors in Dropbox website when using decentraleyes

### ISSUE THREAD

**Issue by koumdros** [Synzvato/decentraleyes#33]
Content Security Policy: The page's settings blocked the loading of a resource at data:application/javascript;charset=UTF-8,%2F**%0A%20*%20Local%20delivery%20by%20Decentraleyes%20(1.2.2).%0A%20*%2F%0A%0A%2F*!%20jQuery%20v1.10.2%20%7C%20(c)%202005%2C%202013%20jQuery%20Foundation%2C%20Inc.%20%7C%20jquery.org%2Flicense%0A*%2F%0A(function(e%2Ct)%7Bvar%20n%2Cr%2Ci%3Dtypeof%20t%2Co%3De.location%2Ca%3De.document%2Cs%3Da.documentElement%2Cl%3De.jQuery%2Cu%3De.%24%2Cc%3D%7B%7D%2Cp%3D%5B%5D%2Cf%3D%221.10.2%22%2Cd%3Dp.concat%2Ch%3Dp.push%2Cg%3Dp.slice%2Cm%3Dp.indexOf%2Cy%3Dc.toString%2Cv%3Dc.hasOwnProperty%2Cb%3Df.trim%2Cx%3Dfunction(e%2Ct)%7Breturn%20new%20x.fn.init(e%2Ct%2Cr)%7D%2Cw%3D%2F%5B%2B-%5D%3F(%3F%3A%5Cd*%5C.%7C)%5Cd%2B(%3F%3A%5BeE%5D%5B%2B-%5D%3F%5Cd%2B%7C)%2F.source%2CT%3D%2F%5CS%2B%2Fg%2CC%3D%2F%5E%5B%5Cs%5CuFEFF%5CxA0%5D%2B%7C%5B%5Cs%5CuFEFF%5CxA0%5D%2B%24%2Fg%2CN%3D%2F%5E(%3F%3A%5Cs*(%3C%5B%5Cw%5CW%5D%2B%3E)%5B%5E%3E%5D*%7C%23(%5B%5Cw-%5D*))%24%2F%2Ck%3D%2F%5E%3C(%5Cw%2B)%5Cs*%5C%2

**Comment by Synzvato** [comment]
Thanks for reporting this issue @koumdros! It's caused by the same underlying issue that's responsible for #16 (and others). That's why I tagged this as a ```duplicate```. It's being worked on as we speak.

**Comment by Synzvato** [comment]
@koumdros I have since filed this as a bug ([```1419459```](https://bugzilla.mozilla.org/show_bug.cgi?id=1419459)) on Mozilla's bugtracker. Upvotes are welcome.
