### ISSUE TITLE
Replace default bundle with a clever caching solution

### ISSUE THREAD

**Issue by maliayas** [Synzvato/decentraleyes#35]
I guess currenly the addon contains library files inside it.

How about if it worked this way:

1. There is a cache folder for thirdparty files. It's empty in the beginning.
2. When a CDN request is made, addon checks if it exists in cache folder.
3. If yes return that.
4. If no, download it, cache and return.

So that no addon update is required in case of library updates. What do you think?

**Comment by Synzvato** [comment]
Hi @maliayas, thanks for your suggestion!

While this is a fairly interesting approach, it would essentially change the core philosophy behind the add-on. Decentraleyes prevents most requests to CDNs by including popular resources. Decisions on what (versions of what libraries) to include are based on web crawling statistics (by [W3Techs](http://w3techs.com/technologies/overview/javascript_library/all)).

This means that at this point, Decentraleyes keeps a lot of websites from breaking whilst fully cutting off major Content Delivery Networks. In that sense, it's more than a clever caching solution.

I do think your idea can be used by people who would like to be able to cache resources that are not present inside the default bundle and I will definitely take it into account. Another approach would be to introduce a standard for custom (shareable) resource bundles (see #6).

Thanks again, I will keep your thoughts in mind!

**Comment by maliayas** [comment]
Ok @Synzvato Thanks.
