### ISSUE TITLE
Provide and maintain RequestPolicy whitelist

### ISSUE THREAD

**Issue by quizilkend** [Synzvato/decentraleyes#36]
Hey!

I use Decentraleyes along with Requestpolicy. Right now it is necessary to whitelist the domains mentioned [here](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#why-doesnt-it-deliver-resources-from-cdns-i-block-using-a-different-add-on) by hand.
It would be useful, if there was a whitelist, which is updatet, with the progress of the Decentraleyes addon.

Best wishes,
Sammy

**Comment by Synzvato** [comment]
Hi, thanks for sharing your thoughts!

While I like the idea, it does not appear to be possible to maintain self-updating whitelists. RequestPolicy does allow users to import domains from a file, but this does not allow for pushing updates to clients. It's also not (evidently) possible to remove old whitelist entries once imported.

This might help users with strict policies with the initial set-up:
```
[origins]
[destinations]
ajax.googleapis.com
ajax.aspnetcdn.com
ajax.microsoft.com
cdnjs.cloudflare.com
code.jquery.com
cdn.jsdelivr.net
yandex.st
libs.baidu.com
lib.sinaapp.com
upcdn.b0.upaiyun.com
[origins-to-destinations]
```

Am I missing something with regards to maintenance?

**Comment by stewie** [comment]
Respectfully, the proposed RP whitelist seems like an insecure (too trusting) approach.

When DE's "retrieve and cache missing" option is enabled, I would hope DE would raise an infobar announcing "page is requesting a not-yet-cached item from a recognized CDN. Allow/Deny". Upon 'Allow' buttonclick, DE would retrieve and permacache the item then trigger a page reload. It's reasonable to expect this will be a seldom-occurring interruption.

**Comment by Synzvato** [comment]
@stewie Thanks for weighing in.

> Respectfully, the proposed RP whitelist seems like an insecure (too trusting) approach.

Note that you can block requests for any missing resources from preferences, and then whitelist any domains of websites that break without the expected libraries. So, adding the CDN domains to your RequestPolicy whitelist does not necessarily mean allowing all requests for missing resources.

**Comment by Synzvato** [comment]
Closing this issue for now (since there now is a static whitelist). I will be sure to re-open this issue if anyone has a strategy for continued maintenance.
