### ISSUE TITLE
Revise injection counter to avoid incessant disk access

### ISSUE THREAD

**Issue by stewie** [Synzvato/decentraleyes#38]
xref: https://github.com/Synzvato/decentraleyes/issues/12

Toward avoiding incessant disk access (updating prefs.js), I'm suggesting that yet another pref (which would be read at startup and stored) should be introduced, enabling the user to opt-out (disable the counter).

Alternatively,  after reading the cumulative total to-date tally at start of session, increment its value in memory only -- updating prefs.js value at shutdown only.

**Comment by Synzvato** [comment]
Definitely important, but I'm happy to say Firefox already does this for us. When you directly edit your preferences in ```about:config```, the settings file ```prefs.js``` is updated immediately. However, updating any settings using ```simple-prefs``` or the Add-ons Manager does not result in disk writes.

I have tested this myself to make absolutely sure, and the ```prefs.js``` file was indeed only updated when I closed ```firefox.exe```, and not directly after updating any of the preference values.
