### ISSUE TITLE
Add install manifest file to the project

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [Synzvato/decentraleyes#42]
Would this be possible so I could install a newer developer edition for the temporary fixes for some websites?

Ah, well, JPM didn't turn out to be that difficult, just kept getting hung up on the bit that required me to be on linux. Got it working just fine. You can close this, ty.

**Comment by Synzvato** [comment]
I'm very happy to hear you managed to get it working! Instead of running a development build, you can also choose to whitelist non-working domains from inside the preferences panel.
