### ISSUE TITLE
Does Twitter Bootstrap from Bootstrap CDN come bundled?

### ISSUE THREAD

**Issue by DeusFigendi** [Synzvato/decentraleyes#43]
I just loaded a website (flattr.com) and got an ugly page. When I allowed policeman to contact to maxcdn.bootstrapcdn.com it worked fine.

But I think it loaded https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css directly from the server and not through the plugin, I think it should.

So this is from my Firefox dev-tools:

````
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
<!-- (…) -->
<script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
````

In the end I am not totally sure if it's loaded by the plugin or directly, can I test/see/prove/investegate if a ressource is loaded from a cdn or hdd? If not maybe it's a good idea to do this in the HTTP-header… like `X-DECENTRAL = "eyes"`.

**Comment by Synzvato** [comment]
Thanks for sharing your concerns!

Bootstrap CDN is not currently supported, but it's likely that it will be soon. At this point bundling scripts only is being looked into (to keep website logic from breaking for users with strict policies). In the future, popular fonts and stylesheets might also find their way into the default bundle.

**Supported:** Google Hosted Libraries, Microsoft Ajax CDN, CDNJS (Cloudflare), jQuery CDN (MaxCDN), jsDelivr (MaxCDN), Yandex CDN, Baidu CDN, Sina Public Resources, and UpYun Libraries.

The response header idea is clever, but Decentraleyes does not send out HTTP responses. This means that seeing an HTTP response automatically means that the request was not prevented.

I hope this answers all of the questions you've been having.

**Comment by DeusFigendi** [comment]
Thanks for the answer.

I didn't know *decentraleyes* comes with "bundled" JavaScripts, I thought it just caches longer but the browser and without always asking for new versions.

>  In the future, popular fonts and stylesheets might also find their way into the default bundle.

Erm you write "default bundle"… are there or will there be non-default bundles? Anyway, I think it should support styles (at least), to fit its aims.

BTW: Great Addon, I think I should install it as default for all my unnerdy friends, because it makes things better (less trackable) with no loss of any comfort.
