### ISSUE TITLE
Does not inject resources that are explicitly blocked

### ISSUE THREAD

**Issue by LifeIsStrange** [Synzvato/decentraleyes#46]
![tmp_4864-screenshot_2016-02-23-14-22-42518828199](https://cloud.githubusercontent.com/assets/12934716/13252947/a5e68048-da39-11e5-9aec-33968382a532.png)

On Android 5.1.1 with uBlock Origin

**Comment by Synzvato** [comment]
Hi @LifeIsStrange, thanks for sharing this! Have you read [this related answer](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#why-doesnt-it-deliver-resources-from-cdns-i-block-using-a-different-add-on) and are you sure you have all of the listed domains whitelisted? Blocked resources will not be locally injected.

I hope this helps. Please let me know if this solved your problems.

**Comment by LifeIsStrange** [comment]
Note that I have manually setted dom.ipc.proccesscount from 1 to 4.  (this is part of es10) 
But I have reset this propertie and nothing change. 
I have now disabled uBlock Origin and this work. 
![tmp_29107-screenshot_2016-02-23-14-51-27518828199](https://cloud.githubusercontent.com/assets/12934716/13253600/1af021e8-da3d-11e5-8e22-9a9163842679.png)
As you can see, uBlock block the Google api jquery script so I think that this script is blocked before than decentraleyes can detect it and so on it will not loccally inject jquery. 
Sorry for my bad english :)

**Comment by LifeIsStrange** [comment]
Oh sorry so this was this "Why doesn't it deliver resources from CDNs I block using a different add-on?

Once a different add-on cancels a request, there's nothing left for Decentraleyes to intercept. You can solve this by whitelisting the domains in question, and making Decentraleyes block requests for missing resources. This will all block traffic to supported CDNs.

Be sure to whitelist ajax.googleapis.com"
Thanks !

**Comment by Synzvato** [comment]
Yes indeed. If you block requests for resources from CDNs that Decentraleyes supports, then these requests will be thrown out and Decentraleyes won't be able to respond to them.

If you want to keep Decentraleyes from automatically contacting a CDN (to prevent pages from breaking) whenever a resource is missing. You could go to the preferences page in the Add-ons Manager, tick "Block requests for missing resources", and add any pages that break as a result to the whitelist.

I'm happy to read that you've managed to resolve the issue!
