### ISSUE TITLE
Testing Utility and ajax.googleapis.com

### ISSUE THREAD

**Issue by tauxeta** [Synzvato/decentraleyes#5]
On the Testing tool page i noticed that when I've the ajax.googleapis.com blocked in uBlock Origin / uMatrix (Which I usually have in most pages) the result I get is:  "The test resource could not be fetched locally or remotely" & "Decentraleyes is not working as intended"
However when I allow the ajax.googleapis I get the "Decentraleyes is fully operational" status.

So if i get this right, Decentraleyes stops working only when you block ajax.googleapis on the specific page that supports this CDN, but works fine in all the other pages with different CDNs, right?

Thanks and keep up the good work!

(Noob question but I need clarification on this)

**Comment by Synzvato** [comment]
Thanks, I'm glad you like it so far!

Yes, you assumed correctly. It intercepts requests for known resources. Once a request has been blocked by uBlock Origin or uMatrix, there's nothing left to intercept or to respond to. 

So, in your case, let's hypothetically say a page makes you request jQuery 2.1.4 from Google Hosted Libraries and your initial blockade leads to page breakage. What you could then do is simply whitelist that specific resource to enable Decentraleyes to intercept it locally.

There's a related answer on this [wiki page](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#why-doesnt-it-deliver-resources-from-cdns-i-block-using-a-different-add-on).
