### ISSUE TITLE
Make add-on compatible with SeaMonkey v2.40

### ISSUE THREAD

**Issue by onodera-punpun** [Synzvato/decentraleyes#50]
See title, using the http://addonconverter.fotokraina.com/ converter it installs the firefox version just fine, so you probably just need to change some "allowed browser version" variable.

**Comment by Synzvato** [comment]
Hi @onodera-punpun, and thanks for your suggestion!

This has been requested before (see issue #29). I'm happy to say that the very next release of this add-on will officially support SeaMonkey versions 2.0a1 and higher.

**Comment by onodera-punpun** [comment]
Oh that's awesome, thanks a lot!

**Comment by Synzvato** [comment]
@onodera-punpun You're very welcome!
