### ISSUE TITLE
Breaks Google Play and probably other sites

### ISSUE THREAD

**Issue by rmenessec** [Synzvato/decentraleyes#52]
This is fairly repeatable. Visit play.google.com, click an app details link, then click "read more". Nothing happens, and the Firefox console is filled with errors about a script being blocked internally - no attribution to an addon or even the offending .js.

This may or may not be caused by having DecentralEyes installed in conjunction with NoScript, uBlock Origin, and Ghostery (5.latest). After pausing / disabling all of the above, though, I finally got GP page elements working again by disabling DecentralEyes. Nothing else I tried had any effect.

**Comment by Synzvato** [comment]
Hi @rmenessec and thanks sharing your concerns!

It's a known problem (see issue #16 for more details on it). However, the most recent version already contains a fix for the domain ```play.google.com```. This is why I'm guessing you have "Block requests for missing resources" enabled in preferences. I think that is what's causing you problems.

Enabling this setting keeps websites from contacting CDNs even if nothing could be injected locally. If you'd like to keep this enabled, just add ```play.google.com``` to the whitelist.

**Comment by rmenessec** [comment]
@Synzvato , whoops. When I see extensions that don't provide their own preferences UI, I tend to assume they don't have any (preferences). I'll check it out.

Sorry for the dupe!

**Comment by Synzvato** [comment]
No worries! hope it helps you resolve the issues. If not, feel free to let me know.

**Comment by rmenessec** [comment]
Nope, that was it. GP Store works fine now. :+1:
