### ISSUE TITLE
Breaks the Dropbox web application

### ISSUE THREAD

**Issue by Bisaloo** [Synzvato/decentraleyes#54]
For a couple of days I'd say, decentraleyes has been breaking [dropbox.com](https://www.dropbox.com/home).

It looks like decentraleyes hasn't been updated since december but it works when I am disabling it so maybe it is a change from dropbox side(?).

I'm using decentraleyes 1.2.2 and ff 45.0

**Comment by Synzvato** [comment]
Hi, thanks for sharing your concerns!

This is a known issue (see #33) where Dropbox's security settings keep Decentraleyes from injecting scripts into the page. For now, adding the domain ```dropbox.com``` to the whitelist (in add-on preferences) should solve your problem. Please let me know if it helps!

After the next update, you should be able to remove the whitelist entry.

**Comment by Bisaloo** [comment]
Oh yeah, I missed that because I didn't check the closed issues. Maybe you should keep one of them open until the release is live.

Thank you for your answer either way!

**Comment by Synzvato** [comment]
No worries! I kept the underlying issue (#16) open and closed all individual reports, but I do agree that its title does not say much about what websites are currently affected.

I'm happy to hear this solves your problems!

**Comment by Synzvato** [comment]
@Bisaloo I've since decided to create a bug ([```1419459```](https://bugzilla.mozilla.org/show_bug.cgi?id=1419459)) on Mozilla's bugtracker. Upvotes are welcome.
