### ISSUE TITLE
Whitelist known incompatible domains by default

### ISSUE THREAD

**Issue by rugk** [Synzvato/decentraleyes#58]
What about adding a default whitelist? Because all users visiting a particular site will have the same issues with this addon.

**Comment by Synzvato** [comment]
Hi @rugk, and thanks for the suggestion!

The latest version of the add-on *(v1.2.2)* already contains a short list of domains that were known to have issues at the time of release. The next version will go a lot further *(see d0277c0)*.

It will feature a mechanism that's able to mark domains as tainted, whenever Decentraleyes detects incompatible security policies. The release will resolve all known website issues.

**Comment by rugk** [comment]
I think users should also be able to remove (specific) sites from the whitelist. (in contrast to now where they can only disable the whole whitelisting feature to disallow whitelisting for all internal whitelisted sites)

**Comment by Synzvato** [comment]
> I think users should also be able to remove (specific) sites from the _[internal]_ whitelist.

It's not really a whitelist. The difference is that whitelisted domains are ignored, whereas files requested by "tainted" domains are always treated as missing (since they are essentially unavailable).
