### ISSUE TITLE
Does the domain whitelist work on my end?

### ISSUE THREAD

**Issue by rugk** [Synzvato/decentraleyes#59]
I have the following settings:
![config](https://cloud.githubusercontent.com/assets/11966684/14159882/f1696ec0-f6d8-11e5-8456-11eca1fdd941.PNG)

However even with the following settings I can still reproduce https://github.com/Synzvato/decentraleyes/issues/16:
![gplayleft](https://cloud.githubusercontent.com/assets/11966684/14159893/02db8472-f6d9-11e5-80be-354d44e51621.PNG)

I can also reproduce https://github.com/Synzvato/decentraleyes/issues/17 and I noticed this issue continued to happen even after I completely disabled this extension. (Does Firefox probably cache some parts?)

As for https://github.com/Synzvato/decentraleyes/issues/24 it is interesting:
* When the domain is in the whitelist everything works correctly and I can see a QR code.
* And when it is not, the site breaks.

Therefore on the last domain it works correctly.

**Comment by Synzvato** [comment]
Hi @rugk, and thanks for sharing your concerns!

>  However even with the following settings [...] I can also reproduce [..] and I noticed this issue continued to happen even after I completely disabled this extension.

The latest release *(v1.2.2)* already auto-ignores ```play.google.com``` as long as you have "Block requests for missing resources" enabled. If not, traffic will be prevented at all costs.

In other words, your settings force Decentraleyes not to react to Google Play in any way, even if you don't put it on your explicit whitelist. This means that the first issue you're experiencing is very likely to be unrelated to Decentraleyes. Do you have any other content blockers installed?

> When the domain *(report-uri.io)* is in the whitelist everything works correctly and I can see a QR code [...] when it is not, the site breaks [...] Therefore on the last domain it works correctly.

I'm happy to hear that the the whitelist-feature appears to be working on your end. This makes it all the more likely that the Google Play bug you're experiencing is unrelated.

Could you please disable all other add-ons (or better yet, hop into safe mode) and try again?

**Comment by rugk** [comment]
Somehow this issue is gone now...
Strange, but nevertheless good.
