### ISSUE TITLE
Add support for local injections of CDN fonts

### ISSUE THREAD

**Issue by Gitoffthelawn** [Synzvato/decentraleyes#60]
Excellent work.

More and more, the most common use of CDN is to download fonts for sites.  Downloading from `fonts.googleapis.com` is unfortunately rampant.

Blocking access to `fonts.googleapis.com` is trivial, but serving the fonts (or similar ones) locally would be ideal.

**Comment by Synzvato** [comment]
@Gitoffthelawn Thanks! This is definitely on the radar. Please see issue #34.

**Comment by Gitoffthelawn** [comment]
Thanks!  And I apologize that I missed #34.
