### ISSUE TITLE
Chromium Support

### ISSUE THREAD

**Issue by AMP648** [Synzvato/decentraleyes#65]
There is clearly a demand for Chromium support. I know you said there's no plans for it but I think you should reconsider this request. Google Chrome is not the only Chromium browser. There are plenty of open source Chrome browsers that follow Mozillas principles. Please consider porting this to chromre.

**Comment by Synzvato** [comment]
Hi @AMP648, thanks for getting in touch. I will post a reply the existing #1 issue.

**Comment by Synzvato** [comment]
Decentraleyes is now available for Chromium-based browsers! As a side note, the Opera-release is finished too, but is currently awaiting moderation. Apologies for the wait, but we could not release while having doubts about various security aspects. All is looking good, though. Thanks for your patience!

**Download and install the package manually**
https://github.com/Synzvato/decentraleyes/releases/tag/v1.3.7

**Install the extension from the Chrome Web Store**
https://chrome.google.com/webstore/detail/decentraleyes/ldpochfccmkkmhdbclfhpagapcfdljkj
