### ISSUE TITLE
Add shorthand mappings for Google Hosted Libraries

### ISSUE THREAD

**Issue by gitarra** [Synzvato/decentraleyes#66]
Example page: https://phoronix.com/scan.php?page=home

The page points to a major version on the CDN: https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js

Which returns the latest subversion 1.8.3.

Decentraleyes local delivery doesnt work here.

**Comment by Synzvato** [comment]
@gitarra Thanks for reporting these missing shorthand notations!

**Comment by gitarra** [comment]
Thanks for the quick fix! =)

**Comment by Gitoffthelawn** [comment]
What does "shorthand" mean in this context?

**Comment by Synzvato** [comment]
> What does "shorthand" mean in this context?

Abbreviated writing method.
