### ISSUE TITLE
Another way to tell if the add-on works on given pages

### ISSUE THREAD

**Issue by Gitoffthelawn** [Synzvato/decentraleyes#68]
Here is a super quick and simple way to tell if Decentraleyes is successfully preventing third-party libraries from being downloaded:
1. Install the [SixOrNot](https://addons.mozilla.org/firefox/addon/sixornot/) extension
2. Add it's toolbar button to a toolbar
3. Click on its toolbar button after any page is loaded

Doing this, you can quickly see every host to which your browser is connecting for the current page.  If a library host is not listed, Decentraleyes is successfully preventing access to that host.

Feel free to add this to the readme, or if you like, I can add this for you.

**Comment by TraderStf** [comment]
FYI, this can help too
ublock, disconnect and the browser inspector - network tab (or ressources)

**Comment by RoxKilly** [comment]
@Gitoffthelawn nice observation and cool add-on.  I typically look at the Network tab of the web developers tools to see what I'm connecting to.  Resources served by Decentraleyes will not show up there.
I also look at the Debugger tab of web developers tools; if you select a script that was served by Decentraleyes, you will notice a comment that the add-on added at the top of the script (unless you unchecked that option in add-on settings)
