### ISSUE TITLE
Remove rare resources from default bundle

### ISSUE THREAD

**Issue by Synzvato** [Synzvato/decentraleyes#7]
I think it's important to find out which versions of which libraries are most commonly used on websites, so that somewhat less popular resources can be removed from the default bundle.

For example, **jQuery 1.5.0** is currently included in Decentraleyes. However, [according to W3Techs](http://w3techs.com/technologies/details/js-jquery/1.5/all), statistically, out of 10.000 websites, only around 6 depend on this particular version of the library. If these numbers are accurate, I'm sure we could put its spot to better use.

Would this be a good source to go by, or does anyone have a better suggestion?

**Comment by Synzvato** [comment]
The library versions below will be removed from the default bundle in an effort to reach a perfect balance between size and effectiveness, in part by making room for other popular libraries:

**AngularJS** - 1.0.7, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.2.11, 1.2.12, 1.2.13, 1.2.14, 1.2.17, 1.2.18, 1.2.19, 1.2.21, 1.2.22, 1.2.24, 1.2.25, 1.2.27, 1.3.1, 1.3.2, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.9, 1.3.12, 1.3.13, 1.3.16, 1.3.17, 1.4.1
See: http://w3techs.com/technologies/details/js-angularjs/1/all

**Backbone.js** - 0.9.0, 0.9.1, 0.9.2, 0.9.9, 0.9.10
See: http://w3techs.com/technologies/details/js-backbone/all/all

**Dojo Toolkit** - 1.1.1, 1.2.0, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 1.4.3, 1.4.4, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.8.0, 1.8.1, 1.8.2, 1.8.4, 1.8.5, 1.8.6, 1.9.2, 1.9.4, 1.9.5, 1.9.6, 1.10.0, 1.10.1, 1.10.2, 1.10.3
See: http://w3techs.com/technologies/details/js-dojo/all/all

**Ember.js** - 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.5.0, 2.0.1
Motivation: Not too common and quite large, so latest the patches of older releases and all most recent versions were kept. All other versions have been removed.

**jQuery UI** - 1.5.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.8.20, 1.8.21, 1.8.22, 1.8.23, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.10.3
Motivation: Splintered and heavy. Personal findings seem to indicate that websites that are hesitant to upgrade, switch to the latest patches of older versions. Selection was optimized accordingly.

**MooTools** - 1.2.2, 1.4.0, 1.4.2, 1.4.3, 1.4.4
See: http://w3techs.com/technologies/details/js-mootools/1/all

**Underscore.js** - 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4
See: http://w3techs.com/technologies/details/js-underscore/1/all

**Yahoo User Interface** - Both versions
Motivation: Large, quite rare, splintered, and no longer maintained.

*Note: In the future, support for custom, importable, bundles will be added to satisfy power-users. This default bundle will, however, remain embedded to make Decentraleyes effective out of the box.*

**Comment by Gitoffthelawn** [comment]
I agree that balance is important, but maybe there is another angle to approach this:  Are there any advantages if the libraries (and possibly fonts in the future) are stored *external* from the extension itself?

That way, users could perform 1-time downloads of packages that will meet the balance that is best for them.  For example, you could offer a jQuery-All package with all versions, and a jQuery-Popular package that only contains versions used by popular sites.

Also, the extension could then only load individual library and font resources on-demand when they are needed, thus reducing memory use and improving browser startup time (if it is impacted).
