### ISSUE TITLE
Add shorthands for Google Hosted Services

### ISSUE THREAD

**Issue by Gitoffthelawn** [Synzvato/decentraleyes#72]
Not loading decentraleyes copy of jquery 1.8 on https://www.creditkarma.com/

Loading this URL from the interwebs:
https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js

**Comment by Synzvato** [comment]
Thanks! This is a known (and resolved) matter. Expect support for these deprecated shorthands to be present in the very next release. Please see #66 for more details.

**Comment by Gitoffthelawn** [comment]
Thanks!
