### ISSUE TITLE
MSDN search broken

### ISSUE THREAD

**Issue by OmegaPhil** [Synzvato/decentraleyes#74]
E.g., search for 'System.Text.StringBuilder': https://social.msdn.microsoft.com/Search/en-US?query=System.Text.StringBuilder&pgArea=header&emptyWatermark=true&ac=4

With decentraleyes enabled, you just get the top and bottom bars, disabled and the site works fine (JavaScript whitelisted through NoScript etc).

Thanks for this sorely needed addon, I'd been wanting something to plug this obvious spying problem for some time.

**Comment by Synzvato** [comment]
Hi @OmegaPhil, and thanks for reporting your findings! I'm not able to reproduce the issues you seem to be experiencing. Maybe some additional details would help?

**Comment by OmegaPhil** [comment]
Apologies - I've just tested in Firefox and it works fine - I use Pale Moon (v26.2), checking the addon versions its obvious the supported version installed here is very old - v1.1.5.1 compared to v1.3 on Firefox.

Sorry for the noise, I'm just stuck with an old version on Pale Moon which you'll probably not want to support - closing.

**Comment by Synzvato** [comment]
I'm happy to say that I will be rolling out manual, tailored, builds for Pale Moon users for as long as absolutely possible (since the internal APIs are starting to diverge). If you'd like to upgrade to v1.3.0, just download and install ```Decentraleyes.v1.3.0-palemoon-unsigned.xpi``` from [this page](https://github.com/Synzvato/decentraleyes/releases/tag/v1.3.0).

**Comment by OmegaPhil** [comment]
Oh sweet :) Thankyou, wasn't expecting that!

Right, after retesting, its my fault - comparing Firefox default and my configuration, 'Block requests for missing sources' was ticked - unticking and it now works... so I'll at least know what to check next time ¬_¬
