### ISSUE TITLE
A tool that simplifies self-hosting Google Fonts

### ISSUE THREAD

**Issue by elypter** [Synzvato/decentraleyes#77]
https://github.com/majodev/google-webfonts-helper

i dont know if this is relevant to the content in decentraleyes but maybe it helps

**Comment by Synzvato** [comment]
@elypter This is bound to contain some valuable insights into how Google Fonts behaves, and I'm quite sure that this will come in handy when adding font-support. Thanks!

**Comment by Gitoffthelawn** [comment]
Here is another project that may help: https://github.com/muzuiget/google-fonts-offliner
