### ISSUE TITLE
Support Are we e10s yet with block missing enabled

### ISSUE THREAD

**Issue by ekaris** [Synzvato/decentraleyes#78]
Add support for arewee10syet.com when blocking all external requests
https://www.arewee10syet.com/

**Comment by Synzvato** [comment]
@ekaris Thanks for the suggestion!

The only way to get there would be to add a not too commonly used version of jQuery to the resource bundle. However, decisions on what to include are based on web crawling statistics by W3Techs.

Focusing on individual websites is not workable and total coverage is not an option. For additional details see related issue #7 and the discussion underneath issue #83.
