### ISSUE TITLE
Support for Google Chrome/Chromium browser?

### ISSUE THREAD

**Issue by vdcbb** [Synzvato/decentraleyes#79]
Any chance you'll be bringing decentraleyes to Google Chrome/Chromium?

**Comment by vdcbb** [comment]
Sorry!

I found this (didn't realize I had to click "closed" when searching): https://github.com/Synzvato/decentraleyes/issues/1

**Comment by Gitoffthelawn** [comment]
@vdcbb Yes, the GitHub search is a bit confusing!

You should be able to close the issue.

**Comment by Synzvato** [comment]
@vdcbb No worries, and thanks for getting in touch! I hope the discussion underneath related issue #1 answers any questions you might be having. If not, feel free to post a comment there.

**Comment by Synzvato** [comment]
Decentraleyes is now available for Chromium-based browsers!
https://github.com/Synzvato/decentraleyes/issues/1#issuecomment-285056496
