### ISSUE TITLE
Support additional Google Hosted Libraries shorthands

### ISSUE THREAD

**Issue by Gitoffthelawn** [Synzvato/decentraleyes#80]
This site: https://www.creditkarma.com

calls

`https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js`

but decentraleyes does not perform the necessary script replacement.

**Comment by Synzvato** [comment]
Thanks for reporting the missing mappings. They were added in commit 61b950f and will be present in the very next release. I hope this addresses your concerns.

**Comment by Gitoffthelawn** [comment]
Thanks.  Sorry for the duplication.  I thought the patches in #66 had already been released.

What does *shorthand notation* mean?

**Comment by Synzvato** [comment]
@Gitoffthelawn No worries! The term is used for short, dynamic, notations of version numbers. For instance,  ```jQuery 1.8``` is a reference to ```jQuery 1.8.3```. These dynamic notations are now deprecated, but all existing notations remain supported, to prevent legacy code from breaking.

**Comment by Gitoffthelawn** [comment]
@Synzvato Thanks!  How does it know it's a reference to `jQuery 1.8.3`?  Does it simply reference the latest sub-point-release of the point-release?  In other words, did it reference `jQuery 1.8.2` before `jQuery 1.8.3` was released (and so on)?

**Comment by Synzvato** [comment]
> Does it simply reference the latest sub-point-release of the point-release? In other words, did it reference jQuery 1.8.2 before jQuery 1.8.3 was released (and so on)?

Yes, that's exactly how it works. At the time it was considered to be a smart way to get automatic patches for minor releases. It's now seen as a bad practice, and only works on older resource versions.

So that means that these exceptions will not require a lot of maintenance, which is nice. I'm happy to hear you're looking forward to the next version! I'm planning to release it soon.

**Comment by Gitoffthelawn** [comment]
Thanks for the explanation.  It's amazing how many "major" sites still use this deprecated notation.
