### ISSUE TITLE
A potentially interesting resource replacer

### ISSUE THREAD

**Issue by Gitoffthelawn** [Synzvato/decentraleyes#82]
Here is another extension that you might find helpful while developing this one:
https://github.com/jiacai2050/gooreplacer

**Comment by renyouguo** [comment]
#69

**Comment by Synzvato** [comment]
@Gitoffthelawn Many thanks for sharing your findings, I'll keep this one in the back of my mind!

**Comment by Gitoffthelawn** [comment]
You're welcome!
