### ISSUE TITLE
Does v1.3.5 require new uBlock Origin or uMatrix rules?

### ISSUE THREAD

**Issue by jjohns71** [Synzvato/decentraleyes#85]
Hi!

Thank you for the great plugin! I noticed in the most recent release ([v1.35](https://github.com/Synzvato/decentraleyes/commit/e595faa5414dcbdece4a1f79e46ef81dfc0e8677)) you added support for additional Google scripts, is there any additional white listing that needs to be done in ublockOrigin or uMatrix that is referenced in the [FAQ](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions) to enable support for the new scripts?

Additionally, in the future would it be possible to **flag users** upon an update to decentraleyes if any new white listing is needed, as well as make it more apparent to **new users** using both decentraleyes and uBlockOrigin and/or uMatrix that they need to white list some domains? (For example it took me a couple months of using decentraleyes to realize I needed to whitelist domains in uBlockOrigin and uMatrix to get any benefit to using this plugin).

Thanks again for the plugin, it is a great idea and look forward to further development!

**Comment by Synzvato** [comment]
> Thank you for the great plugin!

You're very welcome, I'm happy to hear you like the add-on!

> I noticed [...]  you added support for additional Google scripts, is there any additional white listing that needs to be done [...] to enable support for the new scripts?

This update does indeed include new mappings for Google Hosted Libraries, but all of these fall under the domain ```ajax.googleapis.com```, so you won't need to add another entry to your list.

> Additionally, in the future would it be possible to flag users upon an update to decentraleyes if any new white listing is needed

That's a nice suggestion. I think I'll add these kinds of tips to the release notes whenever a new content delivery network is added to the collection (this will probably not happen too often).

> For example it took me a couple months of using decentraleyes to realize I needed to whitelist domains in uBlockOrigin and uMatrix to get any benefit to using this plugin

The pre-made whitelists are not truly mandatory. Quite a few uMatrix or uBlock Origin (advanced mode) users first try a website whilst blocking all third parties, and then enable them one by one if the website doesn't work properly. Decentraleyes serves as a last layer of defence for allowed third parties.

**Add-on Workflow Demonstration**

uBlock Origin ```[blocked]```
uBlock Origin ```[allowed]``` > Decentraleyes ```[file is present]``` > Local Resource
uBlock Origin ```[allowed]``` > Decentraleyes ```[file is not present | allow missing]``` > CDN
uBlock Origin ```[allowed]``` > Decentraleyes ```[file is not present | block missing]```

> Thanks again for the plugin, it is a great idea and look forward to further development!

I'm glad you like the concept, and many thanks for weighing in!

**Comment by jjohns71** [comment]
Thanks for demonstrating the Workflow, that explains it well, perhaps that could be added to the FAQ? It is good to see I was seeing the benefit before the full white list anyway since I did use uBlockOrigin/uMatrix in the manner you described (full block and enable one-by-one on a per site basis).

**Comment by Synzvato** [comment]
@jjohns71 Yes, I fully agree. The FAQ entry will be updated soon, since it's a tad confusing indeed.
