### ISSUE TITLE
Support AlternativeTo with block missing enabled

### ISSUE THREAD

**Issue by jhsagl4a** [Synzvato/decentraleyes#89]
If option `Block request for missing resources` is activated - buttons `all platforms` and `any license` at https://alternativeto.net/tag/font-viewer/ don't work.

**Comment by Synzvato** [comment]
@jhsagl4a Thanks for sharing your concerns!

When you block requests for missing resources, Decentraleyes prevents traffic to content delivery networks, even if the add-on is unable to locally inject required files into the page. This means that page breakage is to be expected when this preference is set to enabled.

You can always use the whitelist feature (in preferences) to add broken pages to your personal list of exceptions in case you want to minimize CDN traffic. You can also decide to disable ```Block requests for missing resources``` and manage traffic using content blockers (e.g. uBlock Origin).

**Add-on Workflow Demonstration**

uBlock Origin ```[blocked]```
uBlock Origin ```[allowed]``` > Decentraleyes ```[file is present]``` > Local Resource
uBlock Origin ```[allowed]``` > Decentraleyes ```[file is not present | allow missing]``` > CDN
uBlock Origin ```[allowed]``` > Decentraleyes ```[file is not present | block missing]```

I hope this helps you with solving the resulting page breakage issue.

**Comment by jhsagl4a** [comment]
May be you can add necessary file in your addon?

**Comment by Synzvato** [comment]
@jhsagl4a Supported libraries are not added on a per-website basis. In order to balance add-on size, and effectiveness Decentraleyes relies on web crawling statistics (see duplicate issue #78).

**Comment by jhsagl4a** [comment]
Hi, it's me, again. I have the same problem on twitch.tv. When that option is activated - log-in button don't work.
