### ISSUE TITLE
Add Twitter Bootstrap to the default bundle

### ISSUE THREAD

**Issue by najjara** [Synzvato/decentraleyes#90]
The Bootstrap framework is the second most popular according to [W3Techs](http://w3techs.com/technologies/overview/javascript_library/all)

It's also offered by many of the supported CDNs (such as Yandex off the top of my head)

Shouldn't it be included?

**Comment by PeterDaveHello** [comment]
BootstrapCDN is not a js lib as jquery or angular, it's more complex here.

**Comment by najjara** [comment]
I'm not a coder nor a webdev, but I see Bootstrap listed as a .js on CDNs. For example:

https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js

Since many websites call `maxcdn.bootstrapcdn.com`, it could be included as well

**Comment by robinpaulson** [comment]
Yeah, I think this is a pretty important library to include, it's very popular.

**Comment by Synzvato** [comment]
@najjara Thanks for sharing your suggestion. This issue is very similar to #37, so I have decided to reopen it. Please post further questions and suggestions there. Thanks again!
