### ISSUE TITLE
Add support for Chromium

### ISSUE THREAD

**Issue by golfingpanda** [Synzvato/decentraleyes#95]
Because chrome participates in the evil agenda of privacy rape for profit I request only support for Chromium, the interweb browser.

**Comment by Kijewski** [comment]
> Because chrome participates in the evil agenda of privacy rape for profit

Sir, might I interest you in switching to [Firefox](https://www.mozilla.org/en-US/firefox/new/) if you hate / fear Chromium so much?  :ghost:

**Comment by Synzvato** [comment]
@golfingpanda Although I wouldn't personally recommend either one of those two solutions to privacy-minded individuals, I do not think excluding compatible environments is going to help anyone. Is this what you mean to propose, or am I misinterpreting your suggestion?

**Comment by Phyks** [comment]
Duplicate of https://github.com/Synzvato/decentraleyes/issues/1.

**Comment by Synzvato** [comment]
Decentraleyes is now available for Chromium-based browsers!
https://github.com/Synzvato/decentraleyes/issues/1#issuecomment-285056496
