### ISSUE TITLE
What's a good debranded Firefox build for OSX?

### ISSUE THREAD

**Issue by golfingpanda** [Synzvato/decentraleyes#96]
Not firefox proper from morally dubious mozilla.  Something akin to waterfox for windows, or palemoon for linux.

**Comment by Synzvato** [comment]
@golfingpanda Your question is not really related to this add-on, but I'll try my best to provide you with a useful answer. Based on [these results](https://alternativeto.net/software/palemoon/?license=opensource&platform=mac&tag=firefox-based) from AlternativeTo, I think GNU IceCat might be the community build you're looking for. It's entirely free (as in libre) and it supports Mac OS X.
