### ISSUE TITLE
I can stop asking large sites to self-host their assets

### ISSUE THREAD

**Issue by golfingpanda** [Synzvato/decentraleyes#97]
Now I can quit writing to large sites asking them to locally cache their asset libraries in the name of user privacy.

kudos

**Comment by Gitoffthelawn** [comment]
Actually, I'm glad you were doing that.

This extension is truly excellent.  At the same time you be aware of the following:

This extension, at least currently, tries to strike a balance between size and frequency of use.  IOW, at this time, it doesn't cover close to everything.  It covers what is most commonly used when looked at a global perspective, but does not necessarily match the sites *you* visit.

When used, it will likely dramatically reduce how often you hit third-party CDN's, but until all sites choose to host their own libraries, it will not eliminate your use of CDN's.

If you have the time and interest, keep sending those letters! :-)
